from django.urls import path

from checklists import portal_views, telegram_views, views
from checklists.telegram_webhook import telegram_webhook


app_name = 'checklists'

urlpatterns = [
    path('telegram/webhook/', telegram_webhook, name='telegram_webhook'),
    path('', views.dashboard, name='dashboard'),
    path('accounts/redirect/', portal_views.post_login_redirect, name='post_login_redirect'),
    path('terminal/', views.today_checklist, name='terminal_home'),
    path(
        'employee/schedule/',
        portal_views.employee_schedule,
        name='employee_schedule',
    ),
    path('checklist/', views.today_checklist, name='terminal_checklist'),
    path(
        'terminal/employee/select/',
        views.select_store_employee,
        name='select_employee',
    ),
    path(
        'terminal/employee/change/',
        views.change_store_employee,
        name='change_employee',
    ),
    path('checklist/today/', views.today_checklist, name='today'),
    path(
        'checklist/today/opening/',
        views.checklist_stage,
        {'section_code': 'opening'},
        name='opening',
    ),
    path(
        'checklist/today/during-day/',
        views.checklist_stage,
        {'section_code': 'during_day'},
        name='during_day',
    ),
    path(
        'checklist/today/closing/',
        views.checklist_stage,
        {'section_code': 'closing'},
        name='closing',
    ),
    path('director/', portal_views.director_dashboard, name='director_root'),
    path('director/dashboard/', portal_views.director_dashboard, name='director_dashboard'),
    path('director/employees/', portal_views.director_employees, name='director_employees'),
    path('director/employees/add/', portal_views.director_employee_add, name='director_employee_add'),
    path('director/employees/<int:employee_id>/edit/', portal_views.director_employee_edit, name='director_employee_edit'),
    path('director/employees/<int:employee_id>/activate/', portal_views.director_employee_activate, name='director_employee_activate'),
    path('director/employees/<int:employee_id>/deactivate/', portal_views.director_employee_deactivate, name='director_employee_deactivate'),
    path('director/shifts/', portal_views.director_shifts, name='director_shifts'),
    path('director/shifts/bulk-create/', portal_views.director_shifts_bulk, name='director_shifts_bulk'),
    path(
        'director/shifts/calendar/update/',
        portal_views.director_shift_calendar_update,
        name='director_shift_calendar_update',
    ),
    path(
        'director/shifts/calendar/copy-week/',
        portal_views.director_shift_calendar_copy_week,
        name='director_shift_calendar_copy_week',
    ),
    path(
        'director/shifts/templates/<int:template_id>/delete/',
        portal_views.director_shift_template_delete,
        name='director_shift_template_delete',
    ),
    path('director/shifts/<str:work_date>/', portal_views.director_shift_date, name='director_shift_date'),
    path('director/shifts/<str:work_date>/copy/', portal_views.director_shift_copy, name='director_shift_copy'),
    path('director/shifts/<str:work_date>/employee/add/', portal_views.director_shift_add, name='director_shift_add'),
    path('director/shifts/<str:work_date>/employee/<int:assignment_id>/edit/', portal_views.director_shift_edit, name='director_shift_edit'),
    path('director/shifts/<str:work_date>/employee/<int:assignment_id>/remove/', portal_views.director_shift_remove, name='director_shift_remove'),
    path('director/questions/', portal_views.director_questions, name='director_questions'),
    path('director/questions/add/', portal_views.director_question_add, name='director_question_add'),
    path('director/questions/reorder/', portal_views.director_questions_reorder, name='director_questions_reorder'),
    path('director/questions/<int:question_id>/edit/', portal_views.director_question_edit, name='director_question_edit'),
    path('director/questions/<int:question_id>/activate/', portal_views.director_question_activate, name='director_question_activate'),
    path('director/questions/<int:question_id>/deactivate/', portal_views.director_question_deactivate, name='director_question_deactivate'),
    path('director/questions/<int:question_id>/delete/', portal_views.director_question_delete, name='director_question_delete'),
    path('director/schedule/', portal_views.director_schedule, name='director_schedule'),
    path('director/notifications/', portal_views.director_notifications, name='director_notifications'),
    path('director/notifications/test/', portal_views.director_notification_test, name='director_notification_test'),
    path('director/tasks/', portal_views.director_tasks, name='director_tasks'),
    path('director/tasks/create/', portal_views.director_task_create, name='director_task_create'),
    path('director/tasks/<int:task_id>/', portal_views.director_task_detail, name='director_task_detail'),
    path('director/tasks/<int:task_id>/edit/', portal_views.director_task_edit, name='director_task_edit'),
    path('director/tasks/<int:task_id>/delete/', portal_views.director_task_delete, name='director_task_delete'),
    path('director/tasks/<int:task_id>/cancel/', portal_views.director_task_cancel, name='director_task_cancel'),
    path(
        'settings/telegram/',
        telegram_views.telegram_settings,
        name='telegram_settings',
    ),
    path(
        'settings/telegram/templates/',
        telegram_views.telegram_templates,
        name='telegram_templates',
    ),
    path(
        'settings/telegram/templates/create/',
        telegram_views.telegram_template_create,
        name='telegram_template_create',
    ),
    path(
        'settings/telegram/templates/preview/',
        telegram_views.telegram_template_preview,
        name='telegram_template_preview_create',
    ),
    path(
        'settings/telegram/templates/<int:template_id>/',
        telegram_views.telegram_template_edit,
        name='telegram_template_edit',
    ),
    path(
        'settings/telegram/templates/<int:template_id>/delete/',
        telegram_views.telegram_template_delete,
        name='telegram_template_delete',
    ),
    path(
        'settings/telegram/templates/<int:template_id>/toggle/',
        telegram_views.telegram_template_toggle,
        name='telegram_template_toggle',
    ),
    path(
        'settings/telegram/templates/<int:template_id>/reset/',
        telegram_views.telegram_template_reset,
        name='telegram_template_reset',
    ),
    path(
        'settings/telegram/templates/<int:template_id>/test/',
        telegram_views.telegram_template_test,
        name='telegram_template_test',
    ),
    path(
        'settings/telegram/templates/<int:template_id>/preview/',
        telegram_views.telegram_template_preview,
        name='telegram_template_preview',
    ),
    path(
        'settings/telegram/users/',
        telegram_views.telegram_users,
        name='telegram_users',
    ),
    path(
        'settings/telegram/users/<int:binding_id>/<str:action>/',
        telegram_views.telegram_binding_action,
        name='telegram_binding_action',
    ),
    path(
        'settings/telegram/profiles/<int:profile_id>/<str:action>/',
        telegram_views.telegram_profile_action,
        name='telegram_profile_action',
    ),
    path(
        'settings/telegram/chats/',
        telegram_views.telegram_chats,
        name='telegram_chats',
    ),
    path(
        'settings/telegram/chats/<int:chat_id>/',
        telegram_views.telegram_chat_edit,
        name='telegram_chat_edit',
    ),
    path(
        'settings/telegram/chats/<int:chat_id>/<str:action>/',
        telegram_views.telegram_chat_action,
        name='telegram_chat_action',
    ),
    path(
        'settings/telegram/queue/',
        telegram_views.telegram_queue,
        name='telegram_queue',
    ),
    path(
        'settings/telegram/queue/<int:message_id>/retry/',
        telegram_views.telegram_queue_retry,
        name='telegram_queue_retry',
    ),
    path(
        'settings/telegram/messages/<int:message_id>/delete/',
        telegram_views.telegram_message_delete,
        name='telegram_message_delete',
    ),
    path('director/reports/', portal_views.director_reports, name='director_reports'),
    path('director/price-tags/', portal_views.price_tags, name='director_price_tags'),
    path('director/price-tags/qr/', portal_views.price_tag_qr, name='price_tag_qr'),
    path('director/price-tags/image/', portal_views.price_tag_image, name='price_tag_image'),
    path(
        'director/price-tags/name-correction/',
        portal_views.price_tag_name_correction,
        name='price_tag_name_correction',
    ),
    path(
        'director/price-tags/category-properties/',
        portal_views.price_tag_category_properties,
        name='price_tag_category_properties',
    ),
    path(
        'director/price-tags/category-promotion/',
        portal_views.price_tag_category_promotion,
        name='price_tag_category_promotion',
    ),
    path('director/price-tags/profile/', portal_views.price_tag_profile, name='price_tag_profile'),
    path('director/reports/daily/', portal_views.director_report_daily, name='director_report_daily'),
    path('director/reports/employees/', portal_views.director_report_employees, name='director_report_employees'),
    path('director/reports/employees/<int:employee_id>/', portal_views.director_report_employee_detail, name='director_report_employee_detail'),
    path('director/reports/revisions/', portal_views.director_report_revisions, name='director_report_revisions'),
    path('director/reports/tasks/', portal_views.director_report_tasks, name='director_report_tasks'),
    path('director/reports/problems/', portal_views.director_report_problems, name='director_report_problems'),
    path('director/reports/recurring/', portal_views.director_report_recurring, name='director_report_recurring'),
    path('director/checklists/<int:checklist_id>/', portal_views.director_checklist_detail, name='director_checklist_detail'),
    path('director/checklists/<int:checklist_id>/stages/<str:section_code>/reopen/', portal_views.director_stage_reopen, name='director_stage_reopen'),
    path('system-admin/', portal_views.system_admin_dashboard, name='system_admin_root'),
    path('system-admin/dashboard/', portal_views.system_admin_dashboard, name='system_admin_dashboard'),
    path('system-admin/reports/', portal_views.system_reports, name='system_reports'),
    path('system-admin/tasks/', portal_views.system_tasks, name='system_tasks'),
    path('system-admin/tasks/<int:task_id>/edit/', portal_views.system_task_edit, name='system_task_edit'),
    path('system-admin/tasks/<int:task_id>/copy/', portal_views.system_task_copy, name='system_task_copy'),
    path('system-admin/tasks/<int:task_id>/delete/', portal_views.system_task_delete, name='system_task_delete'),
    path('system-admin/select-store/', portal_views.system_select_managed_store, name='system_select_managed_store'),
    path('system-admin/stores/', portal_views.system_stores, name='system_stores'),
    path('system-admin/stores/add/', portal_views.system_store_add, name='system_store_add'),
    path('system-admin/stores/<int:store_id>/', portal_views.system_store_detail, name='system_store_detail'),
    path('system-admin/stores/<int:store_id>/edit/', portal_views.system_store_edit, name='system_store_edit'),
    path('system-admin/stores/<int:store_id>/activate/', portal_views.system_store_activate, name='system_store_activate'),
    path('system-admin/stores/<int:store_id>/deactivate/', portal_views.system_store_deactivate, name='system_store_deactivate'),
    path('system-admin/stores/<int:store_id>/delete/', portal_views.system_admin_store_delete, name='system_admin_store_delete'),
    path('system-admin/stores/<int:store_id>/open-director/', portal_views.system_store_open_director, name='system_store_open_director'),
    path('system-admin/users/', portal_views.system_users, name='system_users'),
    path('system-admin/users/add/', portal_views.system_user_add, name='system_user_add'),
    path('system-admin/users/<int:user_id>/', portal_views.system_user_detail, name='system_user_detail'),
    path('system-admin/users/<int:user_id>/edit/', portal_views.system_user_edit, name='system_user_edit'),
    path('system-admin/users/<int:user_id>/delete/', portal_views.system_user_delete, name='system_user_delete'),
    path('system-admin/users/<int:user_id>/stores/add/', portal_views.system_user_membership_add, name='system_user_membership_add'),
    path('system-admin/users/<int:user_id>/stores/<int:membership_id>/remove/', portal_views.system_user_membership_remove, name='system_user_membership_remove'),
    path('system-admin/users/<int:user_id>/reset-password/', portal_views.system_user_reset_password, name='system_user_reset_password'),
    path('system-admin/users/<int:user_id>/activate/', portal_views.system_user_activate, name='system_user_activate'),
    path('system-admin/users/<int:user_id>/deactivate/', portal_views.system_user_deactivate, name='system_user_deactivate'),
    path('system-admin/audit/', portal_views.system_audit, name='system_audit'),
    path(
        'system-admin/audit/store/<int:store_id>/clear/',
        portal_views.system_admin_store_audit_clear,
        name='system_admin_store_audit_clear',
    ),
    path(
        'system-admin/audit/clear-all/',
        portal_views.system_admin_audit_clear_all,
        name='system_admin_audit_clear_all',
    ),
]
