"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

from config.database import build_database_config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-local-development-key-change-before-production',
)

# Менять независимо от SECRET_KEY нельзя после создания дневных чек-листов:
# значение участвует в устойчивом порядке показа пунктов.
RANDOMIZATION_SECRET = os.getenv('RANDOMIZATION_SECRET') or SECRET_KEY

TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_REQUEST_TIMEOUT = float(os.getenv('TELEGRAM_REQUEST_TIMEOUT', '10'))
TELEGRAM_NOTIFICATIONS_ENABLED = os.getenv(
    'TELEGRAM_NOTIFICATIONS_ENABLED',
    'False',
).strip().lower() in {'1', 'true', 'yes', 'on'}
SITE_URL = os.getenv('SITE_URL', 'https://checklist.es-helper.ru').rstrip('/')
BITRIX_WARRANTY_SYNC_URL = os.getenv('BITRIX_WARRANTY_SYNC_URL', '').strip()
BITRIX_WARRANTY_SYNC_SECRET = os.getenv('BITRIX_WARRANTY_SYNC_SECRET', '').strip()
BITRIX_WARRANTY_SYNC_TIMEOUT = float(os.getenv('BITRIX_WARRANTY_SYNC_TIMEOUT', '20'))
WARRANTY_TELEGRAM_FILE_MAX_BYTES = int(
    os.getenv('WARRANTY_TELEGRAM_FILE_MAX_BYTES', str(20 * 1024 * 1024))
)
WARRANTY_PRODUCT_URL_TEMPLATE = os.getenv(
    'WARRANTY_PRODUCT_URL_TEMPLATE',
    'https://pinel.ru/catalog/sku/{product_id}/',
).strip()
TELEGRAM_WEBHOOK_MAX_BODY_BYTES = int(
    os.getenv('TELEGRAM_WEBHOOK_MAX_BODY_BYTES', '1048576')
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').strip().lower() in {'1', 'true', 'yes', 'on'}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]
if 'checklist.es-helper.ru' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('checklist.es-helper.ru')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        'CSRF_TRUSTED_ORIGINS',
        'https://checklist.es-helper.ru',
    ).split(',')
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'checklists.apps.ChecklistsConfig',
    'warranty.apps.WarrantyConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'checklists.portal_context.portal_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = build_database_config(BASE_DIR, os.environ)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'checklists:post_login_redirect'
LOGOUT_REDIRECT_URL = 'login'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
