# Generated by Django 5.2.16 on 2026-08-20 06:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='bitrix', max_length=32, verbose_name='источник')),
                ('external_id', models.PositiveBigIntegerField(verbose_name='ID в источнике')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('service_decision', 'Ожидает решение СЦ'), ('in_progress', 'В работе'), ('customer_wait', 'Ожидаем клиента'), ('diagnostics', 'Диагностика'), ('parts_wait', 'Ожидаем запчасти'), ('ready', 'Готов к выдаче'), ('closed', 'Закрыт')], default='new', max_length=32, verbose_name='статус')),
                ('source_status', models.CharField(blank=True, max_length=64, verbose_name='исходный статус')),
                ('warranty_type', models.CharField(choices=[('warranty', 'По гарантии'), ('non_warranty', 'Не по гарантии')], default='warranty', max_length=24, verbose_name='тип')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('critical', 'Критический')], default='normal', max_length=16, verbose_name='приоритет')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('external_user_id', models.CharField(blank=True, max_length=64, verbose_name='ID клиента в источнике')),
                ('external_created_by_id', models.CharField(blank=True, max_length=64, verbose_name='ID автора в источнике')),
                ('created_by_name', models.CharField(blank=True, max_length=255, verbose_name='создал')),
                ('product_name', models.CharField(blank=True, max_length=500, verbose_name='товар')),
                ('external_product_id', models.CharField(blank=True, max_length=64, verbose_name='ID товара в источнике')),
                ('serial_number', models.CharField(blank=True, max_length=255, verbose_name='серийный номер')),
                ('defect', models.TextField(blank=True, verbose_name='неисправность')),
                ('equipment', models.TextField(blank=True, verbose_name='комплектация')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='дата покупки')),
                ('repair_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='стоимость ремонта')),
                ('product_remains_with_customer', models.BooleanField(default=False, verbose_name='товар у клиента')),
                ('purchased_from_us', models.BooleanField(default=False, verbose_name='куплено у нас')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='срок решения')),
                ('source_created_at', models.DateTimeField(blank=True, null=True, verbose_name='создано в источнике')),
                ('source_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='изменено в источнике')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='закрыто')),
                ('raw_source_data', models.JSONField(blank=True, default=dict, verbose_name='полный снимок источника')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_warranty_claims', to=settings.AUTH_USER_MODEL, verbose_name='ответственный')),
            ],
            options={
                'ordering': ('-source_created_at', '-external_id'),
            },
        ),
        migrations.CreateModel(
            name='WarrantyAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_file_id', models.CharField(max_length=64, verbose_name='ID файла в источнике')),
                ('file', models.FileField(blank=True, upload_to='warranty/attachments/%Y/%m/', verbose_name='файл')),
                ('original_name', models.CharField(blank=True, max_length=500, verbose_name='имя файла')),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('source_path', models.CharField(blank=True, max_length=1000)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='warranty.warrantyclaim')),
            ],
        ),
        migrations.CreateModel(
            name='WarrantyHistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=64)),
                ('kind', models.CharField(choices=[('import', 'Импорт'), ('change', 'Изменение'), ('message', 'Сообщение'), ('telegram', 'Telegram'), ('system', 'Система')], default='change', max_length=16)),
                ('text', models.TextField()),
                ('actor_external_id', models.CharField(blank=True, max_length=64)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='warranty.warrantyclaim')),
            ],
            options={
                'ordering': ('occurred_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WarrantyTelegramThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, max_length=64)),
                ('topic_id', models.CharField(blank=True, help_text='Рекомендуется отдельная тема форума вместо отдельной группы.', max_length=64)),
                ('state', models.CharField(choices=[('planned', 'Ожидает создания'), ('active', 'Активна'), ('archived', 'Архивирована'), ('restore_pending', 'Ожидает восстановления'), ('error', 'Ошибка')], default='planned', max_length=24)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_thread', to='warranty.warrantyclaim')),
            ],
        ),
        migrations.CreateModel(
            name='WarrantyTelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_message_id', models.CharField(blank=True, max_length=64)),
                ('direction', models.CharField(choices=[('inbound', 'Входящее'), ('outbound', 'Исходящее')], max_length=16)),
                ('sender_external_id', models.CharField(blank=True, max_length=64)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='warranty.warrantytelegramthread')),
            ],
            options={
                'ordering': ('sent_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WarrantyWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('diagnostic', 'Диагностика'), ('labor', 'Работа'), ('part', 'Запчасть'), ('delivery', 'Доставка')], max_length=16)),
                ('name', models.CharField(max_length=500)),
                ('sku', models.CharField(blank=True, max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_warranty_covered', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='warranty.warrantyclaim')),
            ],
        ),
        migrations.AddIndex(
            model_name='warrantyclaim',
            index=models.Index(fields=['status', 'priority'], name='warranty_wa_status_1b1919_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantyclaim',
            index=models.Index(fields=['phone'], name='warranty_wa_phone_4663b8_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantyclaim',
            index=models.Index(fields=['serial_number'], name='warranty_wa_serial__b6d054_idx'),
        ),
        migrations.AddConstraint(
            model_name='warrantyclaim',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_warranty_claim_source_id'),
        ),
        migrations.AddConstraint(
            model_name='warrantyattachment',
            constraint=models.UniqueConstraint(fields=('claim', 'external_file_id'), name='unique_warranty_attachment_source_id'),
        ),
        migrations.AddConstraint(
            model_name='warrantyhistoryevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('claim', 'external_id'), name='unique_warranty_history_external_id'),
        ),
        migrations.AddConstraint(
            model_name='warrantytelegrammessage',
            constraint=models.UniqueConstraint(condition=models.Q(('telegram_message_id', ''), _negated=True), fields=('thread', 'telegram_message_id'), name='unique_warranty_telegram_message'),
        ),
    ]
