# Generated by Django 5.2.16 on 2026-08-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyTelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_id', models.CharField(blank=True, max_length=64, verbose_name='Telegram peer ID')),
                ('chat_id', models.CharField(blank=True, max_length=64, verbose_name='Bot API chat ID')),
                ('use_forum_topics', models.BooleanField(default=True, verbose_name='отдельная тема на обращение')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='интеграция включена')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'настройка Telegram гарантийного отдела',
                'verbose_name_plural': 'настройки Telegram гарантийного отдела',
            },
        ),
    ]
