# Generated by Django 5.2.16 on 2026-08-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0003_seed_warranty_telegram_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantytelegramthread',
            name='state',
            field=models.CharField(choices=[('planned', 'Ожидает создания'), ('active', 'Активна'), ('close_pending', 'Ожидает закрытия'), ('archived', 'Архивирована'), ('restore_pending', 'Ожидает восстановления'), ('error', 'Ошибка')], default='planned', max_length=24),
        ),
    ]
