# Generated by Django 5.2.16 on 2026-08-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0011_warrantytelegrammessage_audit_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenworksDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=120, unique=True, verbose_name='артикул Greenworks')),
                ('links', models.JSONField(default=list, verbose_name='чертежи')),
                ('refreshed_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'чертёж Greenworks',
                'verbose_name_plural': 'чертежи Greenworks',
                'ordering': ('article',),
            },
        ),
    ]
