# Generated by Django 5.2.16 on 2026-08-20 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0015_set_warranty_status_icons'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyCustomerBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, max_length=255, verbose_name='токен клиентского бота')),
                ('webhook_secret_token', models.CharField(blank=True, max_length=255, verbose_name='секрет webhook')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='бот включён')),
                ('ocr_api_key', models.CharField(blank=True, max_length=255, verbose_name='ключ OpenAI для распознавания')),
                ('ocr_model', models.CharField(default='gpt-4.1-mini', max_length=64, verbose_name='модель распознавания')),
                ('welcome_text', models.TextField(default='Здравствуйте! Я помогу оформить гарантийное обращение. Пришлите фото этикетки изделия.', verbose_name='приветствие')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'настройка клиентского бота гарантии',
                'verbose_name_plural': 'настройки клиентского бота гарантии',
            },
        ),
        migrations.CreateModel(
            name='WarrantyCustomerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.CharField(max_length=64, unique=True)),
                ('chat_id', models.CharField(max_length=64)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='телефон')),
                ('article', models.CharField(blank=True, max_length=255, verbose_name='артикул')),
                ('serial_number', models.CharField(blank=True, max_length=255, verbose_name='серийный номер')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='дата покупки')),
                ('step', models.CharField(choices=[('label', 'Фото этикетки'), ('warranty_card', 'Фото гарантийного талона'), ('receipt', 'Фото чека'), ('phone', 'Телефон'), ('full_name', 'ФИО'), ('article', 'Артикул вручную'), ('serial', 'Серийный номер вручную'), ('purchase_date', 'Дата покупки вручную'), ('ready', 'Подтверждение'), ('submitted', 'Оформлено')], default='label', max_length=32)),
                ('external_claim_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('telegram_message_ids', models.JSONField(blank=True, default=list)),
                ('raw_ocr_data', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='warrantyclaim',
            name='article',
            field=models.CharField(blank=True, max_length=255, verbose_name='артикул'),
        ),
        migrations.CreateModel(
            name='WarrantyCustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('label', 'Этикетка'), ('warranty_card', 'Гарантийный талон'), ('receipt', 'Чек')], max_length=24)),
                ('telegram_file_id', models.CharField(max_length=255)),
                ('telegram_message_id', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to='warranty/customer/%Y/%m/')),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='warranty.warrantycustomersession')),
            ],
        ),
    ]
