# Generated by Django 5.2.16 on 2026-08-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0016_warrantycustomerbotsettings_warrantycustomersession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyCustomerUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.PositiveBigIntegerField(unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
