# Generated by Django 5.2.16 on 2026-08-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0017_warrantycustomerupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantycustomerbotsettings', name='ocr_api_key',
            field=models.CharField(blank=True, help_text='Основной способ распознавания. Если ключ пуст или сервис недоступен, используется OCR.space.', max_length=255, verbose_name='ключ OpenAI для распознавания'),
        ),
        migrations.AlterField(
            model_name='warrantycustomerbotsettings', name='ocr_model',
            field=models.CharField(default='gpt-4.1-mini', max_length=64, verbose_name='модель OpenAI'),
        ),
        migrations.AddField(
            model_name='warrantycustomerbotsettings', name='ocr_space_api_key',
            field=models.CharField(blank=True, help_text='Получите бесплатный ключ на https://ocr.space/ocrapi. При ошибке будет использован локальный Tesseract.', max_length=255, verbose_name='бесплатный ключ OCR.space'),
        ),
        migrations.AddField(
            model_name='warrantycustomerbotsettings',
            name='tesseract_command',
            field=models.CharField(default='tesseract', help_text='Путь или имя исполняемого файла. Используется только как резерв.', max_length=255, verbose_name='команда Tesseract'),
        ),
        migrations.AddField(
            model_name='warrantycustomerbotsettings',
            name='webhook_last_error',
            field=models.TextField(blank=True, verbose_name='ошибка webhook'),
        ),
        migrations.AddField(
            model_name='warrantycustomerbotsettings',
            name='webhook_registered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='webhook зарегистрирован'),
        ),
        migrations.AddField(
            model_name='warrantycustomerbotsettings',
            name='webhook_url',
            field=models.URLField(blank=True, verbose_name='адрес webhook'),
        ),
    ]
