# Generated by Django 5.2.16 on 2026-08-20 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0018_remove_warrantycustomerbotsettings_ocr_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyCustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.CharField(max_length=64, unique=True)),
                ('chat_id', models.CharField(max_length=64)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='телефон')),
                ('consent_version', models.CharField(max_length=32)),
                ('consent_text', models.TextField()),
                ('consent_message_id', models.CharField(blank=True, max_length=64)),
                ('consent_accepted_at', models.DateTimeField()),
                ('consent_revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='warrantycustomerbotsettings',
            name='consent_version',
            field=models.CharField(default='1.0', help_text='Увеличьте версию при изменении оператора, целей, состава данных или сервисов OCR — бот запросит согласие заново.', max_length=32, verbose_name='версия согласия'),
        ),
        migrations.AddField(
            model_name='warrantycustomerbotsettings',
            name='consent_withdrawal_contact',
            field=models.CharField(default='service@pinel.ru', max_length=255, verbose_name='контакт для отзыва согласия'),
        ),
        migrations.AddField(
            model_name='warrantycustomerbotsettings',
            name='personal_data_operator',
            field=models.CharField(default='ИП Савченко Е.В.', max_length=500, verbose_name='оператор персональных данных'),
        ),
        migrations.AddField(
            model_name='warrantycustomerbotsettings',
            name='personal_data_operator_address',
            field=models.CharField(default='195176, г. Санкт-Петербург, ул. Апрельская, д. 5', max_length=500, verbose_name='адрес оператора'),
        ),
        migrations.AddField(
            model_name='warrantycustomerbotsettings',
            name='privacy_policy_url',
            field=models.URLField(default='https://pinel.ru/privacy-policy/', verbose_name='политика обработки данных'),
        ),
        migrations.AddField(
            model_name='warrantycustomersession',
            name='mode',
            field=models.CharField(choices=[('claim', 'Рекламация'), ('registration', 'Регистрация покупки')], default='claim', max_length=24),
        ),
        migrations.AlterField(
            model_name='warrantycustomersession',
            name='step',
            field=models.CharField(choices=[('menu', 'Главное меню'), ('consent', 'Согласие на обработку данных'), ('label', 'Фото этикетки'), ('warranty_card', 'Фото гарантийного талона'), ('receipt', 'Фото чека'), ('phone', 'Телефон'), ('full_name', 'ФИО'), ('article', 'Артикул вручную'), ('serial', 'Серийный номер вручную'), ('purchase_date', 'Дата покупки вручную'), ('ready', 'Подтверждение'), ('submitted', 'Оформлено')], default='label', max_length=32),
        ),
        migrations.CreateModel(
            name='WarrantyProductRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=255, verbose_name='артикул')),
                ('serial_number', models.CharField(max_length=255, verbose_name='серийный номер')),
                ('purchase_date', models.DateField(verbose_name='дата покупки')),
                ('raw_ocr_data', models.JSONField(blank=True, default=dict)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('label_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warranty.warrantycustomerdocument')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='warranty.warrantycustomerprofile')),
                ('receipt_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warranty.warrantycustomerdocument')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'serial_number'), name='unique_registered_product_serial')],
            },
        ),
    ]
