# Generated by Django 5.2.16 on 2026-08-20 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0019_warrantycustomerprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantycustomersession',
            name='selected_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warranty.warrantyproductregistration'),
        ),
        migrations.AlterField(
            model_name='warrantycustomersession',
            name='step',
            field=models.CharField(choices=[('menu', 'Главное меню'), ('consent', 'Согласие на обработку данных'), ('product', 'Выбор зарегистрированного товара'), ('label', 'Фото этикетки'), ('warranty_card', 'Фото гарантийного талона'), ('receipt', 'Фото чека'), ('phone', 'Телефон'), ('full_name', 'ФИО'), ('article', 'Артикул вручную'), ('serial', 'Серийный номер вручную'), ('purchase_date', 'Дата покупки вручную'), ('ready', 'Подтверждение'), ('submitted', 'Оформлено')], default='label', max_length=32),
        ),
    ]
