# Generated by Django 5.2.16 on 2026-08-20 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0020_warrantycustomersession_selected_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantycustomerbotsettings',
            name='support_group_id',
            field=models.CharField(blank=True, help_text='ID отдельной Telegram supergroup с включёнными темами, например -1001234567890.', max_length=64, verbose_name='ID группы поддержки'),
        ),
        migrations.CreateModel(
            name='WarrantyCustomerSupportThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.CharField(max_length=64, unique=True)),
                ('customer_chat_id', models.CharField(max_length=64)),
                ('support_chat_id', models.CharField(max_length=64)),
                ('message_thread_id', models.CharField(max_length=64)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('telegram_message_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('support_chat_id', 'message_thread_id'), name='unique_customer_support_topic')],
            },
        ),
        migrations.CreateModel(
            name='WarrantyCustomerSupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('customer', 'От клиента'), ('support', 'От поддержки')], max_length=16)),
                ('source_message_id', models.CharField(max_length=64)),
                ('copied_message_id', models.CharField(blank=True, max_length=64)),
                ('sender_external_id', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='warranty.warrantycustomersupportthread')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('thread', 'direction', 'source_message_id'), name='unique_customer_support_message')],
            },
        ),
    ]
