# Generated by Django 5.2.16 on 2026-08-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0021_warrantycustomerbotsettings_support_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantycustomerbotsettings',
            name='ocr_model',
            field=models.CharField(choices=[('gpt-4.1-nano', 'GPT-4.1 nano — самый дешёвый'), ('gpt-4.1-mini', 'GPT-4.1 mini — баланс цены и качества'), ('gpt-4.1', 'GPT-4.1 — максимальное качество серии'), ('gpt-4o-mini', 'GPT-4o mini — экономичный'), ('gpt-4o', 'GPT-4o — высокое качество')], default='gpt-4.1-mini', help_text='Если выбранную модель отключат, бот автоматически переключится на GPT-4.1 nano.', max_length=64, verbose_name='модель OpenAI'),
        ),
    ]
