# Generated by Django 5.2.16 on 2026-08-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0022_alter_warrantycustomerbotsettings_ocr_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantycustomerbotsettings',
            name='support_group_id',
            field=models.CharField(blank=True, help_text='Можно вставить номер из Telegram без префикса, например 4462669970.', max_length=64, verbose_name='ID группы поддержки (без -100)'),
        ),
    ]
