# Generated by Django 5.2.16 on 2026-08-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0023_alter_warrantycustomerbotsettings_support_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantycustomerbotsettings',
            name='consent_text_template',
            field=models.TextField(default='Почти готово. Перед тем как сохранить ваши контакты, нужно согласие на обработку персональных данных.\n\nЧто сохраним:\n• ФИО и телефон\n• Telegram ID\n• фото этикеток, чека и гарантийного талона\n• артикулы, серийные номера и дату покупки\n\nЗачем: зарегистрировать электронную гарантию, оформлять обращения без поездки в магазин и связываться с вами по гарантии.\n\nОператор: {operator}, {operator_address}.\n{recognition_notice}\nСогласие действует до достижения этих целей или до отзыва. Отозвать согласие: {withdrawal_contact}.\nПолитика обработки данных: {privacy_policy_url}\n\nСогласие добровольное. Нажимая «Согласен», вы подтверждаете согласие на получение, запись, хранение, уточнение, использование и удаление указанных данных с применением автоматизированных средств.', help_text='Можно использовать: {operator}, {operator_address}, {recognition_notice}, {withdrawal_contact}, {privacy_policy_url}.', verbose_name='текст согласия в боте'),
        ),
    ]
