# Generated by Django 5.2.16 on 2026-07-16 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('code', models.SlugField(verbose_name='код')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
            ],
            options={
                'verbose_name': 'раздел чек-листа',
                'verbose_name_plural': 'разделы чек-листа',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
            ],
            options={
                'verbose_name': 'шаблон чек-листа',
                'verbose_name_plural': 'шаблоны чек-листов',
                'ordering': ('store', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='код')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=64, verbose_name='часовой пояс')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
            ],
            options={
                'verbose_name': 'магазин',
                'verbose_name_plural': 'магазины',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст пункта')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('comment_required_on_failure', models.BooleanField(default=True, verbose_name='требовать комментарий при невыполнении')),
                ('allow_not_applicable', models.BooleanField(default=False, verbose_name='разрешить «не применимо»')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklistsection', verbose_name='раздел')),
            ],
            options={
                'verbose_name': 'пункт чек-листа',
                'verbose_name_plural': 'пункты чек-листа',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='номер версии')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована'), ('archived', 'В архиве')], default='draft', max_length=16, verbose_name='статус')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='опубликована')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checklist_versions', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='checklists.checklisttemplate', verbose_name='шаблон')),
            ],
            options={
                'verbose_name': 'версия шаблона',
                'verbose_name_plural': 'версии шаблонов',
                'ordering': ('template', '-version_number'),
            },
        ),
        migrations.AddField(
            model_name='checklistsection',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='checklists.checklisttemplateversion', verbose_name='версия шаблона'),
        ),
        migrations.CreateModel(
            name='DailyChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_date', models.DateField(verbose_name='дата чек-листа')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Завершён'), ('reopened', 'Открыт повторно')], default='draft', max_length=16, verbose_name='статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='начат')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='завершён')),
                ('reopened_at', models.DateTimeField(blank=True, null=True, verbose_name='открыт повторно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_daily_checklists', to=settings.AUTH_USER_MODEL, verbose_name='повторно открыл')),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_checklists', to='checklists.checklisttemplateversion', verbose_name='версия шаблона')),
            ],
            options={
                'verbose_name': 'ежедневный чек-лист',
                'verbose_name_plural': 'ежедневные чек-листы',
                'ordering': ('-checklist_date', 'store', 'employee'),
            },
        ),
        migrations.CreateModel(
            name='DailyChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(max_length=50, verbose_name='код раздела')),
                ('section_name', models.CharField(max_length=255, verbose_name='название раздела')),
                ('section_sort_order', models.PositiveIntegerField(verbose_name='порядок раздела')),
                ('item_text', models.TextField(verbose_name='текст пункта')),
                ('item_sort_order', models.PositiveIntegerField(verbose_name='порядок пункта')),
                ('comment_required_on_failure', models.BooleanField(default=True, verbose_name='требовать комментарий при невыполнении')),
                ('allow_not_applicable', models.BooleanField(default=False, verbose_name='разрешить «не применимо»')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('daily_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.dailychecklist', verbose_name='ежедневный чек-лист')),
                ('source_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_snapshots', to='checklists.checklistitem', verbose_name='исходный пункт')),
            ],
            options={
                'verbose_name': 'снимок пункта чек-листа',
                'verbose_name_plural': 'снимки пунктов чек-листов',
                'ordering': ('section_sort_order', 'item_sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChecklistAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('completed', 'Выполнено'), ('failed', 'Не выполнено'), ('not_applicable', 'Не применимо')], default='pending', max_length=20, verbose_name='статус')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='время ответа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_answers', to=settings.AUTH_USER_MODEL, verbose_name='ответил')),
                ('daily_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='checklists.dailychecklistitem', verbose_name='пункт ежедневного чек-листа')),
            ],
            options={
                'verbose_name': 'ответ на пункт чек-листа',
                'verbose_name_plural': 'ответы на пункты чек-листа',
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('employee', 'Сотрудник'), ('manager', 'Менеджер'), ('administrator', 'Администратор')], default='employee', max_length=20, verbose_name='роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='checklists.store', verbose_name='магазин')),
            ],
            options={
                'verbose_name': 'профиль сотрудника',
                'verbose_name_plural': 'профили сотрудников',
                'ordering': ('store', 'user__username'),
            },
        ),
        migrations.AddField(
            model_name='dailychecklist',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_checklists', to='checklists.employeeprofile', verbose_name='сотрудник'),
        ),
        migrations.AddField(
            model_name='dailychecklist',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_checklists', to='checklists.store', verbose_name='магазин'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_templates', to='checklists.store', verbose_name='магазин'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=100, verbose_name='тип объекта')),
                ('object_id', models.CharField(max_length=255, verbose_name='ID объекта')),
                ('action', models.CharField(choices=[('daily_checklist_created', 'Создан ежедневный чек-лист'), ('answer_status_changed', 'Изменён статус ответа'), ('answer_comment_changed', 'Изменён комментарий ответа'), ('daily_checklist_completed', 'Чек-лист завершён'), ('daily_checklist_reopened', 'Чек-лист открыт повторно'), ('template_version_published', 'Версия шаблона опубликована')], max_length=50, verbose_name='действие')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='поле')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='старое значение')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='новое значение')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='инициатор')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='checklists.store', verbose_name='магазин')),
            ],
            options={
                'verbose_name': 'запись журнала изменений',
                'verbose_name_plural': 'журнал изменений',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='checklisttemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version_number'), name='unique_template_version_number'),
        ),
        migrations.AddConstraint(
            model_name='checklisttemplateversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('template',), name='one_published_version_per_template'),
        ),
        migrations.AddConstraint(
            model_name='checklisttemplateversion',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), ('published_at__isnull', False), _connector='OR'), name='published_or_archived_version_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='checklistsection',
            constraint=models.UniqueConstraint(fields=('version', 'code'), name='unique_section_code_per_version'),
        ),
        migrations.AddConstraint(
            model_name='dailychecklist',
            constraint=models.UniqueConstraint(fields=('store', 'employee', 'checklist_date'), name='unique_employee_daily_checklist'),
        ),
    ]
