# Generated by Django 5.2.16 on 2026-07-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='checklisttemplateversion',
            name='one_published_version_per_template',
        ),
    ]
