# Generated by Django 5.2.16 on 2026-07-16 16:29

import hashlib
from datetime import datetime, time, timedelta
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


STAGE_SCHEDULE = (
    ('opening', time(0), time(11), False),
    ('during_day', time(11), time(20), False),
    ('closing', time(20), time(0), True),
)


def populate_stages_and_display_order(apps, schema_editor):
    DailyChecklist = apps.get_model('checklists', 'DailyChecklist')
    DailyChecklistItem = apps.get_model('checklists', 'DailyChecklistItem')
    DailyChecklistStage = apps.get_model('checklists', 'DailyChecklistStage')
    secret = getattr(settings, 'RANDOMIZATION_SECRET', settings.SECRET_KEY)
    now = timezone.now()

    stages = []
    for daily in DailyChecklist.objects.select_related('store').iterator():
        try:
            store_tz = ZoneInfo(daily.store.timezone)
        except ZoneInfoNotFoundError:
            store_tz = ZoneInfo('UTC')
        for section_code, opens_time, deadline_time, next_day in STAGE_SCHEDULE:
            opens_at = datetime.combine(
                daily.checklist_date,
                opens_time,
                tzinfo=store_tz,
            )
            deadline_date = daily.checklist_date + (
                timedelta(days=1) if next_day else timedelta()
            )
            deadline_at = datetime.combine(
                deadline_date,
                deadline_time,
                tzinfo=store_tz,
            )
            if daily.status == 'completed':
                # У старой схемы нет времени отдельных этапов. Сохраняем
                # известное время всего дня как техническое для каждого этапа;
                # при NULL оставляем NULL и не придумываем исторические данные.
                status = 'completed'
                completed_at = daily.completed_at
            else:
                completed_at = None
                if now < opens_at:
                    status = 'locked'
                elif now >= deadline_at:
                    status = 'overdue'
                else:
                    status = 'available'
            stages.append(
                DailyChecklistStage(
                    daily_checklist=daily,
                    section_code=section_code,
                    status=status,
                    opens_at=opens_at,
                    deadline_at=deadline_at,
                    completed_at=completed_at,
                )
            )
    DailyChecklistStage.objects.bulk_create(stages)

    items = list(
        DailyChecklistItem.objects.select_related('daily_checklist').all()
    )
    for item in items:
        daily = item.daily_checklist
        identity = item.source_item_id or item.pk
        payload = (
            f'{secret}|{daily.employee_id}|{daily.checklist_date.isoformat()}|'
            f'{item.section_code}|{identity}'
        ).encode()
        item.display_order = int.from_bytes(
            hashlib.sha256(payload).digest()[:8],
            'big',
        ) & (2**63 - 1)
    DailyChecklistItem.objects.bulk_update(items, ('display_order',))


def reverse_population(apps, schema_editor):
    DailyChecklistItem = apps.get_model('checklists', 'DailyChecklistItem')
    DailyChecklistStage = apps.get_model('checklists', 'DailyChecklistStage')
    DailyChecklistStage.objects.all().delete()
    DailyChecklistItem.objects.all().update(display_order=0)


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_remove_checklisttemplateversion_one_published_version_per_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChecklistStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(choices=[('opening', 'Утренние задачи'), ('during_day', 'Дневные задачи'), ('closing', 'Вечерние задачи')], max_length=20, verbose_name='этап')),
                ('status', models.CharField(choices=[('locked', 'Недоступен'), ('available', 'Доступен'), ('completed', 'Завершён вовремя'), ('overdue', 'Просрочен'), ('completed_late', 'Завершён с опозданием')], default='locked', max_length=20, verbose_name='статус')),
                ('opens_at', models.DateTimeField(verbose_name='открывается')),
                ('deadline_at', models.DateTimeField(verbose_name='срок завершения')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='завершён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
            ],
            options={
                'verbose_name': 'временной этап чек-листа',
                'verbose_name_plural': 'временные этапы чек-листов',
                'ordering': ('opens_at', 'id'),
            },
        ),
        migrations.AlterModelOptions(
            name='dailychecklistitem',
            options={'ordering': ('section_sort_order', 'display_order', 'id'), 'verbose_name': 'снимок пункта чек-листа', 'verbose_name_plural': 'снимки пунктов чек-листов'},
        ),
        migrations.AddField(
            model_name='dailychecklistitem',
            name='display_order',
            field=models.PositiveBigIntegerField(default=0, verbose_name='порядок показа'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('daily_checklist_created', 'Создан ежедневный чек-лист'), ('answer_status_changed', 'Изменён статус ответа'), ('answer_comment_changed', 'Изменён комментарий ответа'), ('daily_checklist_completed', 'Чек-лист завершён'), ('daily_checklist_reopened', 'Чек-лист открыт повторно'), ('checklist_stage_completed', 'Этап чек-листа завершён'), ('template_version_published', 'Версия шаблона опубликована')], max_length=50, verbose_name='действие'),
        ),
        migrations.AddIndex(
            model_name='dailychecklistitem',
            index=models.Index(fields=['daily_checklist', 'section_code', 'display_order'], name='daily_stage_display_idx'),
        ),
        migrations.AddField(
            model_name='dailycheckliststage',
            name='daily_checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='checklists.dailychecklist', verbose_name='ежедневный чек-лист'),
        ),
        migrations.RunPython(
            populate_stages_and_display_order,
            reverse_population,
        ),
        migrations.AddConstraint(
            model_name='dailycheckliststage',
            constraint=models.UniqueConstraint(fields=('daily_checklist', 'section_code'), name='unique_daily_checklist_stage'),
        ),
    ]
