# Generated by Django 5.2.16 on 2026-07-16 16:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


def create_default_store_schedules(apps, schema_editor):
    Store = apps.get_model('checklists', 'Store')
    StoreChecklistSchedule = apps.get_model(
        'checklists',
        'StoreChecklistSchedule',
    )
    StoreChecklistSchedule.objects.bulk_create(
        [StoreChecklistSchedule(store=store) for store in Store.objects.all()],
        ignore_conflicts=True,
    )


def remove_default_store_schedules(apps, schema_editor):
    StoreChecklistSchedule = apps.get_model(
        'checklists',
        'StoreChecklistSchedule',
    )
    StoreChecklistSchedule.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_dailycheckliststage_alter_dailychecklistitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreChecklistSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(default=datetime.time(9, 0), help_text='Изменение применяется только к новым ежедневным чек-листам', verbose_name='начало работы')),
                ('morning_deadline', models.TimeField(default=datetime.time(11, 0), help_text='Изменение применяется только к новым ежедневным чек-листам', verbose_name='дедлайн утреннего этапа')),
                ('daytime_deadline', models.TimeField(default=datetime.time(20, 0), help_text='Изменение применяется только к новым ежедневным чек-листам', verbose_name='дедлайн дневного этапа')),
                ('closing_deadline', models.TimeField(default=datetime.time(22, 0), help_text='Изменение применяется только к новым ежедневным чек-листам', verbose_name='дедлайн вечернего этапа')),
                ('warning_minutes_before', models.PositiveIntegerField(default=30, help_text='Изменение применяется только к новым ежедневным чек-листам', verbose_name='предупреждать за, минут')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Изменение применяется только к новым ежедневным чек-листам', verbose_name='уведомления включены')),
                ('is_active', models.BooleanField(default=True, help_text='Изменение применяется только к новым ежедневным чек-листам', verbose_name='активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('store', models.OneToOneField(help_text='Изменение применяется только к новым ежедневным чек-листам', on_delete=django.db.models.deletion.CASCADE, related_name='checklist_schedule', to='checklists.store', verbose_name='магазин')),
            ],
            options={
                'verbose_name': 'расписание чек-листа магазина',
                'verbose_name_plural': 'расписания чек-листов магазинов',
                'constraints': [models.CheckConstraint(condition=models.Q(('warning_minutes_before__gt', 0)), name='schedule_warning_minutes_positive')],
            },
        ),
        migrations.RunPython(
            create_default_store_schedules,
            remove_default_store_schedules,
        ),
    ]
