# Generated by Django 5.2.16 on 2026-07-16 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_storechecklistschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('daily_checklist_created', 'Создан ежедневный чек-лист'), ('answer_status_changed', 'Изменён статус ответа'), ('answer_comment_changed', 'Изменён комментарий ответа'), ('daily_checklist_completed', 'Чек-лист завершён'), ('daily_checklist_reopened', 'Чек-лист открыт повторно'), ('checklist_stage_completed', 'Этап чек-листа завершён'), ('telegram_notification_sent', 'Telegram-уведомление отправлено'), ('telegram_notification_failed', 'Ошибка Telegram-уведомления'), ('template_version_published', 'Версия шаблона опубликована')], max_length=50, verbose_name='действие'),
        ),
        migrations.CreateModel(
            name='StoreNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=255, verbose_name='Telegram chat ID')),
                ('warning_enabled', models.BooleanField(default=True, verbose_name='предупреждения включены')),
                ('overdue_enabled', models.BooleanField(default=True, verbose_name='уведомления о просрочке включены')),
                ('completed_late_enabled', models.BooleanField(default=True, verbose_name='уведомления о позднем завершении включены')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='checklists.store', verbose_name='магазин')),
            ],
            options={
                'verbose_name': 'настройка уведомлений магазина',
                'verbose_name_plural': 'настройки уведомлений магазинов',
            },
        ),
        migrations.CreateModel(
            name='ChecklistNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('deadline_warning', 'Скоро дедлайн'), ('overdue', 'Просрочка'), ('completed_late', 'Завершено с опозданием')], max_length=24, verbose_name='тип уведомления')),
                ('scheduled_for', models.DateTimeField(verbose_name='запланировано на')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('failed', 'Ошибка отправки')], default='pending', max_length=16, verbose_name='статус')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='попыток')),
                ('sending_started_at', models.DateTimeField(blank=True, null=True, verbose_name='отправка начата')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='отправлено')),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram message ID')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='checklists.dailycheckliststage', verbose_name='этап')),
            ],
            options={
                'verbose_name': 'уведомление чек-листа',
                'verbose_name_plural': 'уведомления чек-листов',
                'ordering': ('scheduled_for', 'id'),
                'indexes': [models.Index(fields=['status'], name='notification_status_idx'), models.Index(fields=['scheduled_for'], name='notification_schedule_idx'), models.Index(fields=['stage', 'notification_type'], name='notification_stage_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('stage', 'notification_type'), name='unique_notification_type_stage')],
            },
        ),
    ]
