# Generated by Django 5.2.16 on 2026-07-16 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_individual_employee_history(apps, schema_editor):
    EmployeeProfile = apps.get_model('checklists', 'EmployeeProfile')
    StoreEmployee = apps.get_model('checklists', 'StoreEmployee')
    ChecklistAnswer = apps.get_model('checklists', 'ChecklistAnswer')
    DailyChecklistStage = apps.get_model('checklists', 'DailyChecklistStage')
    AuditLog = apps.get_model('checklists', 'AuditLog')

    employee_by_user = {}
    for profile in EmployeeProfile.objects.select_related('user').iterator():
        user = profile.user
        display_name = (
            f'{user.first_name} {user.last_name}'.strip() or user.username
        )
        employee = StoreEmployee.objects.create(
            store_id=profile.store_id,
            first_name=user.first_name.strip() or user.username,
            last_name=user.last_name.strip(),
            display_name=display_name,
            is_active=profile.is_active and user.is_active,
            sort_order=0,
        )
        employee_by_user[user.pk] = employee.pk

    answers = []
    for answer in ChecklistAnswer.objects.exclude(
        answered_by_id__isnull=True
    ).iterator():
        employee_id = employee_by_user.get(answer.answered_by_id)
        if employee_id:
            answer.answered_by_employee_id = employee_id
            answer.last_edited_by_employee_id = employee_id
            answers.append(answer)
    ChecklistAnswer.objects.bulk_update(
        answers,
        ('answered_by_employee', 'last_edited_by_employee'),
    )

    audit_logs = []
    stage_actor = {}
    for log in AuditLog.objects.exclude(actor_id__isnull=True).iterator():
        employee_id = employee_by_user.get(log.actor_id)
        if employee_id:
            log.employee_id = employee_id
            audit_logs.append(log)
            if (
                log.action == 'checklist_stage_completed'
                and log.object_type == 'checklists.dailycheckliststage'
            ):
                stage_actor[log.object_id] = employee_id
    AuditLog.objects.bulk_update(audit_logs, ('employee',))

    stages = []
    for stage in DailyChecklistStage.objects.exclude(
        completed_at__isnull=True
    ).iterator():
        employee_id = stage_actor.get(str(stage.pk))
        stage.first_completed_at = stage.completed_at
        stage.completed_by_employee_id = employee_id
        stage.first_completed_by_employee_id = employee_id
        stage.last_edited_by_employee_id = employee_id
        stages.append(stage)
    DailyChecklistStage.objects.bulk_update(
        stages,
        (
            'first_completed_at',
            'completed_by_employee',
            'first_completed_by_employee',
            'last_edited_by_employee',
        ),
    )


def reverse_individual_employee_history(apps, schema_editor):
    AnswerRevision = apps.get_model('checklists', 'AnswerRevision')
    DailyShiftAssignment = apps.get_model('checklists', 'DailyShiftAssignment')
    ChecklistAnswer = apps.get_model('checklists', 'ChecklistAnswer')
    DailyChecklistStage = apps.get_model('checklists', 'DailyChecklistStage')
    AuditLog = apps.get_model('checklists', 'AuditLog')
    StoreEmployee = apps.get_model('checklists', 'StoreEmployee')
    AnswerRevision.objects.all().delete()
    DailyShiftAssignment.objects.all().delete()
    ChecklistAnswer.objects.all().update(
        answered_by_employee=None,
        last_edited_by_employee=None,
    )
    DailyChecklistStage.objects.all().update(
        completed_by_employee=None,
        first_completed_by_employee=None,
        last_edited_by_employee=None,
        first_completed_at=None,
    )
    AuditLog.objects.all().update(employee=None)
    StoreEmployee.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_alter_auditlog_action_storenotificationsettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckliststage',
            name='first_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='впервые завершён'),
        ),
        migrations.AddField(
            model_name='dailycheckliststage',
            name='reopened_count',
            field=models.PositiveIntegerField(default=0, verbose_name='количество повторных открытий'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('daily_checklist_created', 'Создан ежедневный чек-лист'), ('answer_status_changed', 'Изменён статус ответа'), ('answer_comment_changed', 'Изменён комментарий ответа'), ('daily_checklist_completed', 'Чек-лист завершён'), ('daily_checklist_reopened', 'Чек-лист открыт повторно'), ('checklist_stage_completed', 'Этап чек-листа завершён'), ('telegram_notification_sent', 'Telegram-уведомление отправлено'), ('telegram_notification_failed', 'Ошибка Telegram-уведомления'), ('answer_revised', 'Ответ изменён с указанием причины'), ('template_version_published', 'Версия шаблона опубликована')], max_length=50, verbose_name='действие'),
        ),
        migrations.AlterField(
            model_name='dailychecklist',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_checklists', to='checklists.employeeprofile', verbose_name='сотрудник'),
        ),
        migrations.CreateModel(
            name='StoreEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='фамилия')),
                ('display_name', models.CharField(max_length=255, verbose_name='отображаемое имя')),
                ('personnel_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='табельный номер')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_employees', to='checklists.store', verbose_name='магазин')),
            ],
            options={
                'verbose_name': 'сотрудник магазина',
                'verbose_name_plural': 'сотрудники магазина',
                'ordering': ('sort_order', 'display_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DailyShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='дата работы')),
                ('is_responsible_for_checklist', models.BooleanField(default=True, verbose_name='ответственный за чек-лист')),
                ('shift_start', models.TimeField(blank=True, null=True, verbose_name='начало смены')),
                ('shift_end', models.TimeField(blank=True, null=True, verbose_name='окончание смены')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift_assignments', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_assignments', to='checklists.store', verbose_name='магазин')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_assignments', to='checklists.storeemployee', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'назначение на смену',
                'verbose_name_plural': 'назначения на смену',
                'ordering': ('-work_date', 'employee__sort_order', 'employee__display_name'),
            },
        ),
        migrations.CreateModel(
            name='AnswerRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('completed', 'Выполнено'), ('failed', 'Не выполнено'), ('not_applicable', 'Не применимо')], max_length=20, verbose_name='предыдущий статус')),
                ('new_status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('completed', 'Выполнено'), ('failed', 'Не выполнено'), ('not_applicable', 'Не применимо')], max_length=20, verbose_name='новый статус')),
                ('previous_comment', models.TextField(blank=True, verbose_name='предыдущий комментарий')),
                ('new_comment', models.TextField(blank=True, verbose_name='новый комментарий')),
                ('change_reason', models.TextField(verbose_name='причина изменения')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='изменено')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='checklists.checklistanswer', verbose_name='ответ')),
                ('changed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_revisions', to=settings.AUTH_USER_MODEL, verbose_name='технический пользователь')),
                ('changed_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answer_revisions', to='checklists.storeemployee', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'ревизия ответа',
                'verbose_name_plural': 'ревизии ответов',
                'ordering': ('-changed_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='checklists.storeemployee', verbose_name='фактический сотрудник'),
        ),
        migrations.AddField(
            model_name='checklistanswer',
            name='answered_by_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers_given', to='checklists.storeemployee', verbose_name='первым ответил сотрудник'),
        ),
        migrations.AddField(
            model_name='checklistanswer',
            name='last_edited_by_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers_last_edited', to='checklists.storeemployee', verbose_name='последним изменил сотрудник'),
        ),
        migrations.AddField(
            model_name='dailycheckliststage',
            name='completed_by_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_stages', to='checklists.storeemployee', verbose_name='завершил сотрудник'),
        ),
        migrations.AddField(
            model_name='dailycheckliststage',
            name='first_completed_by_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_completed_stages', to='checklists.storeemployee', verbose_name='впервые завершил сотрудник'),
        ),
        migrations.AddField(
            model_name='dailycheckliststage',
            name='last_edited_by_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_edited_stages', to='checklists.storeemployee', verbose_name='последним изменил сотрудник'),
        ),
        migrations.CreateModel(
            name='StoreTerminalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_account', to='checklists.store', verbose_name='магазин')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='store_terminal_account', to=settings.AUTH_USER_MODEL, verbose_name='пользователь терминала')),
            ],
            options={
                'verbose_name': 'терминальный аккаунт магазина',
                'verbose_name_plural': 'терминальные аккаунты магазинов',
            },
        ),
        migrations.AddField(
            model_name='dailychecklist',
            name='terminal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_checklists', to='checklists.storeterminalaccount', verbose_name='терминальный аккаунт'),
        ),
        migrations.RunPython(
            migrate_individual_employee_history,
            reverse_individual_employee_history,
        ),
        migrations.AddConstraint(
            model_name='dailychecklist',
            constraint=models.UniqueConstraint(fields=('store', 'terminal_account', 'checklist_date'), name='unique_terminal_daily_checklist'),
        ),
        migrations.AddConstraint(
            model_name='dailychecklist',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('employee__isnull', False), ('terminal_account__isnull', True)), models.Q(('employee__isnull', True), ('terminal_account__isnull', False)), _connector='OR'), name='daily_checklist_one_account_type'),
        ),
        migrations.AddConstraint(
            model_name='storeemployee',
            constraint=models.UniqueConstraint(fields=('store', 'personnel_number'), name='unique_store_personnel_number'),
        ),
        migrations.AddConstraint(
            model_name='dailyshiftassignment',
            constraint=models.UniqueConstraint(fields=('store', 'employee', 'work_date'), name='unique_store_employee_work_date'),
        ),
    ]
