# Generated by Django 5.2.16 on 2026-07-16 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_access_roles(apps, schema_editor):
    EmployeeProfile = apps.get_model('checklists', 'EmployeeProfile')
    StoreTerminalAccount = apps.get_model('checklists', 'StoreTerminalAccount')
    User = apps.get_model('auth', 'User')

    terminals_by_user = {
        terminal.user_id: terminal
        for terminal in StoreTerminalAccount.objects.all().iterator()
    }
    profiles_by_user = {
        profile.user_id: profile
        for profile in EmployeeProfile.objects.all().iterator()
    }

    for profile in profiles_by_user.values():
        user = User.objects.get(pk=profile.user_id)
        terminal = terminals_by_user.get(profile.user_id)
        if terminal is not None:
            profile.role = 'store_account'
            profile.store_id = terminal.store_id
            profile.is_active = bool(
                profile.is_active and user.is_active and terminal.is_active
            )
        elif user.is_superuser or profile.role == 'administrator':
            profile.role = 'system_admin'
            profile.store_id = None
            profile.is_active = bool(profile.is_active and user.is_active)
        elif profile.role == 'manager' and profile.store_id is not None:
            profile.role = 'store_director'
            profile.is_active = bool(profile.is_active and user.is_active)
        else:
            # Legacy employee accounts remain for historical foreign keys but
            # receive no new business role or login access.
            profile.role = None
            profile.is_active = False
        profile.save(update_fields=('role', 'store', 'is_active'))

    for user_id, terminal in terminals_by_user.items():
        if user_id in profiles_by_user:
            continue
        user = User.objects.get(pk=user_id)
        EmployeeProfile.objects.create(
            user_id=user_id,
            store_id=terminal.store_id,
            role='store_account',
            is_active=bool(user.is_active and terminal.is_active),
        )

    for user in User.objects.filter(is_superuser=True).iterator():
        if EmployeeProfile.objects.filter(user_id=user.pk).exists():
            continue
        EmployeeProfile.objects.create(
            user_id=user.pk,
            store_id=None,
            role='system_admin',
            is_active=user.is_active,
        )


def reverse_access_roles(apps, schema_editor):
    AuditLog = apps.get_model('checklists', 'AuditLog')
    EmployeeProfile = apps.get_model('checklists', 'EmployeeProfile')
    Store = apps.get_model('checklists', 'Store')

    fallback_store = Store.objects.order_by('pk').first()
    if fallback_store is None:
        EmployeeProfile.objects.all().delete()
        return
    AuditLog.objects.filter(store_id__isnull=True).update(
        store_id=fallback_store.pk
    )
    for profile in EmployeeProfile.objects.all().iterator():
        if profile.role == 'store_director':
            profile.role = 'manager'
        elif profile.role == 'system_admin':
            profile.role = 'administrator'
        else:
            profile.role = 'employee'
        if profile.store_id is None:
            profile.store_id = fallback_store.pk
        profile.save(update_fields=('role', 'store'))


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0006_dailycheckliststage_first_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание или инструкция'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='effective_from',
            field=models.DateField(blank=True, null=True, verbose_name='действует с'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='effective_until',
            field=models.DateField(blank=True, null=True, verbose_name='действует до'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='обязателен'),
        ),
        migrations.AddField(
            model_name='dailychecklistitem',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='обязателен'),
        ),
        migrations.AddField(
            model_name='dailychecklistitem',
            name='item_description',
            field=models.TextField(blank=True, verbose_name='описание или инструкция'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('daily_checklist_created', 'Создан ежедневный чек-лист'), ('answer_status_changed', 'Изменён статус ответа'), ('answer_comment_changed', 'Изменён комментарий ответа'), ('daily_checklist_completed', 'Чек-лист завершён'), ('daily_checklist_reopened', 'Чек-лист открыт повторно'), ('checklist_stage_completed', 'Этап чек-листа завершён'), ('telegram_notification_sent', 'Telegram-уведомление отправлено'), ('telegram_notification_failed', 'Ошибка Telegram-уведомления'), ('answer_revised', 'Ответ изменён с указанием причины'), ('template_version_published', 'Версия шаблона опубликована'), ('store_created', 'Магазин создан'), ('store_updated', 'Магазин изменён'), ('store_activated', 'Магазин активирован'), ('store_deactivated', 'Магазин деактивирован'), ('user_created', 'Пользователь создан'), ('user_updated', 'Пользователь изменён'), ('user_activated', 'Пользователь активирован'), ('user_deactivated', 'Пользователь деактивирован'), ('user_role_changed', 'Роль пользователя изменена'), ('user_store_changed', 'Магазин пользователя изменён'), ('user_password_reset', 'Пароль пользователя сброшен'), ('store_employee_created', 'Сотрудник создан'), ('store_employee_updated', 'Сотрудник изменён'), ('store_employee_activated', 'Сотрудник активирован'), ('store_employee_deactivated', 'Сотрудник деактивирован'), ('checklist_question_created', 'Вопрос создан'), ('checklist_question_updated', 'Вопрос изменён'), ('checklist_question_activated', 'Вопрос активирован'), ('checklist_question_deactivated', 'Вопрос деактивирован'), ('checklist_questions_reordered', 'Вопросы переупорядочены'), ('store_schedule_updated', 'Расписание магазина изменено'), ('store_notification_settings_updated', 'Настройки уведомлений изменены'), ('telegram_test_message_sent', 'Тест Telegram отправлен'), ('checklist_stage_reopened', 'Этап повторно открыт'), ('shift_assignment_created', 'Назначение на смену создано'), ('shift_assignment_updated', 'Назначение на смену изменено'), ('shift_assignment_deleted', 'Назначение на смену удалено'), ('shift_assignments_bulk_created', 'Назначения на смены созданы массово')], max_length=50, verbose_name='действие'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='checklists.store', verbose_name='магазин'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('store_account', 'Аккаунт магазина'), ('store_director', 'Директор магазина'), ('system_admin', 'Администратор системы')], default='store_account', max_length=20, null=True, verbose_name='роль'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='checklists.store', verbose_name='магазин'),
        ),
        migrations.RunPython(migrate_access_roles, reverse_access_roles),
        migrations.AddConstraint(
            model_name='employeeprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role__in', ('store_account', 'store_director')), ('store__isnull', False)), models.Q(('role', 'system_admin'), ('store__isnull', True)), models.Q(('is_active', False), ('role__isnull', True)), _connector='OR'), name='access_profile_role_store_consistent'),
        ),
    ]
