# Generated by Django 5.2.16 on 2026-07-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0007_checklistitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('daily_checklist_created', 'Создан ежедневный чек-лист'), ('answer_status_changed', 'Изменён статус ответа'), ('answer_comment_changed', 'Изменён комментарий ответа'), ('daily_checklist_completed', 'Чек-лист завершён'), ('daily_checklist_reopened', 'Чек-лист открыт повторно'), ('checklist_stage_completed', 'Этап чек-листа завершён'), ('telegram_notification_sent', 'Telegram-уведомление отправлено'), ('telegram_notification_failed', 'Ошибка Telegram-уведомления'), ('answer_revised', 'Ответ изменён с указанием причины'), ('template_version_published', 'Версия шаблона опубликована'), ('store_created', 'Магазин создан'), ('store_updated', 'Магазин изменён'), ('store_activated', 'Магазин активирован'), ('store_deactivated', 'Магазин деактивирован'), ('user_created', 'Пользователь создан'), ('user_updated', 'Пользователь изменён'), ('user_activated', 'Пользователь активирован'), ('user_deactivated', 'Пользователь деактивирован'), ('user_role_changed', 'Роль пользователя изменена'), ('user_store_changed', 'Магазин пользователя изменён'), ('user_password_reset', 'Пароль пользователя сброшен'), ('store_employee_created', 'Сотрудник создан'), ('store_employee_updated', 'Сотрудник изменён'), ('store_employee_activated', 'Сотрудник активирован'), ('store_employee_deactivated', 'Сотрудник деактивирован'), ('checklist_question_created', 'Вопрос создан'), ('checklist_question_updated', 'Вопрос изменён'), ('checklist_question_activated', 'Вопрос активирован'), ('checklist_question_deactivated', 'Вопрос деактивирован'), ('checklist_question_deleted', 'Вопрос удалён'), ('checklist_question_removed_from_template', 'Вопрос исключён из новых чек-листов'), ('checklist_questions_reordered', 'Вопросы переупорядочены'), ('store_schedule_updated', 'Расписание магазина изменено'), ('store_notification_settings_updated', 'Настройки уведомлений изменены'), ('telegram_test_message_sent', 'Тест Telegram отправлен'), ('checklist_stage_reopened', 'Этап повторно открыт'), ('shift_assignment_created', 'Назначение на смену создано'), ('shift_assignment_updated', 'Назначение на смену изменено'), ('shift_assignment_deleted', 'Назначение на смену удалено'), ('shift_assignments_bulk_created', 'Назначения на смены созданы массово')], max_length=50, verbose_name='действие'),
        ),
    ]
