# Generated by Django 5.2.16 on 2026-07-16 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_status_types_and_revision_items(apps, schema_editor):
    ChecklistItem = apps.get_model('checklists', 'ChecklistItem')
    DailyChecklistItem = apps.get_model('checklists', 'DailyChecklistItem')
    AnswerRevision = apps.get_model('checklists', 'AnswerRevision')

    ChecklistItem.objects.all().update(answer_type='status')
    DailyChecklistItem.objects.all().update(answer_type_snapshot='status')
    for revision in AnswerRevision.objects.select_related('answer').iterator():
        revision.daily_item_id = revision.answer.daily_item_id
        revision.save(update_fields=('daily_item',))


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0009_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answerrevision',
            name='daily_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answer_revisions', to='checklists.dailychecklistitem', verbose_name='пункт ежедневного чек-листа'),
        ),
        migrations.AddField(
            model_name='answerrevision',
            name='new_integer_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='новое числовое значение'),
        ),
        migrations.AddField(
            model_name='answerrevision',
            name='previous_integer_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='предыдущее числовое значение'),
        ),
        migrations.AddField(
            model_name='checklistanswer',
            name='integer_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='целочисленный ответ'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='answer_type',
            field=models.CharField(choices=[('status', 'Статус выполнения'), ('integer', 'Целое число')], default='status', max_length=16, verbose_name='тип ответа'),
        ),
        migrations.AddField(
            model_name='dailychecklistitem',
            name='answer_type_snapshot',
            field=models.CharField(choices=[('status', 'Статус выполнения'), ('integer', 'Целое число')], default='status', max_length=16, verbose_name='тип ответа'),
        ),
        migrations.RunPython(
            populate_status_types_and_revision_items,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='answerrevision',
            name='daily_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_revisions', to='checklists.dailychecklistitem', verbose_name='пункт ежедневного чек-листа'),
        ),
        migrations.AlterField(
            model_name='answerrevision',
            name='new_status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает ответа'), ('completed', 'Выполнено'), ('failed', 'Не выполнено'), ('not_applicable', 'Не применимо')], max_length=20, null=True, verbose_name='новый статус'),
        ),
        migrations.AlterField(
            model_name='answerrevision',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает ответа'), ('completed', 'Выполнено'), ('failed', 'Не выполнено'), ('not_applicable', 'Не применимо')], max_length=20, null=True, verbose_name='предыдущий статус'),
        ),
        migrations.AlterField(
            model_name='checklistanswer',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает ответа'), ('completed', 'Выполнено'), ('failed', 'Не выполнено'), ('not_applicable', 'Не применимо')], default='pending', max_length=20, null=True, verbose_name='статус'),
        ),
        migrations.AddConstraint(
            model_name='checklistanswer',
            constraint=models.CheckConstraint(condition=models.Q(('status__isnull', True), ('integer_value__isnull', True), _connector='OR'), name='answer_status_integer_exclusive'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('daily_checklist_created', 'Создан ежедневный чек-лист'), ('answer_status_changed', 'Изменён статус ответа'), ('answer_comment_changed', 'Изменён комментарий ответа'), ('daily_checklist_completed', 'Чек-лист завершён'), ('daily_checklist_reopened', 'Чек-лист открыт повторно'), ('checklist_stage_completed', 'Этап чек-листа завершён'), ('telegram_notification_sent', 'Telegram-уведомление отправлено'), ('telegram_notification_failed', 'Ошибка Telegram-уведомления'), ('answer_revised', 'Ответ изменён с указанием причины'), ('template_version_published', 'Версия шаблона опубликована'), ('store_created', 'Магазин создан'), ('store_updated', 'Магазин изменён'), ('store_activated', 'Магазин активирован'), ('store_deactivated', 'Магазин деактивирован'), ('store_deleted', 'Магазин удалён'), ('store_deactivated_with_history', 'Магазин с историей деактивирован'), ('audit_log_cleared', 'Журнал действий очищен'), ('user_created', 'Пользователь создан'), ('user_updated', 'Пользователь изменён'), ('user_activated', 'Пользователь активирован'), ('user_deactivated', 'Пользователь деактивирован'), ('user_role_changed', 'Роль пользователя изменена'), ('user_store_changed', 'Магазин пользователя изменён'), ('user_password_reset', 'Пароль пользователя сброшен'), ('store_employee_created', 'Сотрудник создан'), ('store_employee_updated', 'Сотрудник изменён'), ('store_employee_activated', 'Сотрудник активирован'), ('store_employee_deactivated', 'Сотрудник деактивирован'), ('checklist_question_created', 'Вопрос создан'), ('checklist_question_updated', 'Вопрос изменён'), ('checklist_question_activated', 'Вопрос активирован'), ('checklist_question_deactivated', 'Вопрос деактивирован'), ('checklist_question_deleted', 'Вопрос удалён'), ('checklist_question_removed_from_template', 'Вопрос исключён из новых чек-листов'), ('checklist_questions_reordered', 'Вопросы переупорядочены'), ('store_schedule_updated', 'Расписание магазина изменено'), ('store_notification_settings_updated', 'Настройки уведомлений изменены'), ('telegram_test_message_sent', 'Тест Telegram отправлен'), ('checklist_stage_reopened', 'Этап повторно открыт'), ('shift_assignment_created', 'Назначение на смену создано'), ('shift_assignment_updated', 'Назначение на смену изменено'), ('shift_assignment_deleted', 'Назначение на смену удалено'), ('shift_assignments_bulk_created', 'Назначения на смены созданы массово')], max_length=50, verbose_name='действие'),
        ),
    ]
