# Generated by Django 5.2.16 on 2026-07-18 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0014_redesign_telegram_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('daily_checklist_created', 'Создан ежедневный чек-лист'), ('answer_status_changed', 'Изменён статус ответа'), ('answer_comment_changed', 'Изменён комментарий ответа'), ('daily_checklist_completed', 'Чек-лист завершён'), ('daily_checklist_reopened', 'Чек-лист открыт повторно'), ('checklist_stage_completed', 'Этап чек-листа завершён'), ('telegram_notification_sent', 'Telegram-уведомление отправлено'), ('telegram_notification_failed', 'Ошибка Telegram-уведомления'), ('answer_revised', 'Ответ изменён с указанием причины'), ('template_version_published', 'Версия шаблона опубликована'), ('store_created', 'Магазин создан'), ('store_updated', 'Магазин изменён'), ('store_activated', 'Магазин активирован'), ('store_deactivated', 'Магазин деактивирован'), ('store_deleted', 'Магазин удалён'), ('store_deactivated_with_history', 'Магазин с историей деактивирован'), ('audit_log_cleared', 'Журнал действий очищен'), ('user_created', 'Пользователь создан'), ('user_updated', 'Пользователь изменён'), ('user_activated', 'Пользователь активирован'), ('user_deactivated', 'Пользователь деактивирован'), ('user_role_changed', 'Роль пользователя изменена'), ('user_store_changed', 'Магазин пользователя изменён'), ('user_password_reset', 'Пароль пользователя сброшен'), ('store_employee_created', 'Сотрудник создан'), ('store_employee_updated', 'Сотрудник изменён'), ('store_employee_activated', 'Сотрудник активирован'), ('store_employee_deactivated', 'Сотрудник деактивирован'), ('checklist_question_created', 'Вопрос создан'), ('checklist_question_updated', 'Вопрос изменён'), ('checklist_question_activated', 'Вопрос активирован'), ('checklist_question_deactivated', 'Вопрос деактивирован'), ('checklist_question_deleted', 'Вопрос удалён'), ('checklist_question_removed_from_template', 'Вопрос исключён из новых чек-листов'), ('checklist_questions_reordered', 'Вопросы переупорядочены'), ('store_schedule_updated', 'Расписание магазина изменено'), ('store_notification_settings_updated', 'Настройки уведомлений изменены'), ('telegram_test_message_sent', 'Тест Telegram отправлен'), ('checklist_stage_reopened', 'Этап повторно открыт'), ('shift_assignment_created', 'Назначение на смену создано'), ('shift_assignment_updated', 'Назначение на смену изменено'), ('shift_assignment_deleted', 'Назначение на смену удалено'), ('shift_assignments_bulk_created', 'Назначения на смены созданы массово'), ('telegram_system_settings_updated', 'Системные настройки Telegram изменены'), ('telegram_store_chat_created', 'Telegram-чат создан'), ('telegram_store_chat_updated', 'Telegram-чат изменён'), ('telegram_store_chat_deleted', 'Telegram-чат удалён'), ('telegram_template_updated', 'Шаблон Telegram изменён'), ('telegram_template_created', 'Шаблон Telegram создан'), ('telegram_template_deleted', 'Шаблон Telegram удалён'), ('telegram_template_enabled', 'Шаблон Telegram включён'), ('telegram_template_disabled', 'Шаблон Telegram выключен'), ('telegram_template_reset', 'Шаблон Telegram восстановлен'), ('telegram_template_test_sent', 'Тест шаблона Telegram поставлен в очередь'), ('telegram_binding_approved', 'Привязка Telegram подтверждена'), ('telegram_binding_disabled', 'Привязка Telegram отключена'), ('telegram_task_created', 'Разовая задача создана'), ('telegram_task_completed', 'Разовая задача выполнена'), ('telegram_task_failed', 'Разовая задача не выполнена'), ('telegram_test_sent', 'Тест Telegram поставлен в очередь'), ('telegram_delivery_failed', 'Доставка Telegram завершилась ошибкой')], max_length=50, verbose_name='действие'),
        ),
        migrations.AlterField(
            model_name='telegrammessagetemplate',
            name='event_code',
            field=models.CharField(choices=[('test_message', 'Тестовое сообщение'), ('stage_reminder_30', 'Напоминание за 30 минут'), ('stage_reminder_10', 'Напоминание за 10 минут'), ('stage_closed', 'Этап закрыт'), ('stage_overdue', 'Этап просрочен'), ('incomplete_tasks', 'Невыполненные задачи'), ('task_created', 'Разовая задача создана'), ('task_completed', 'Разовая задача выполнена'), ('task_failed', 'Разовая задача не выполнена'), ('telegram_binding_pending', 'Привязка ожидает подтверждения'), ('telegram_binding_approved', 'Привязка подтверждена'), ('telegram_delivery_failed', 'Ошибка доставки')], max_length=40, verbose_name='событие'),
        ),
        migrations.AddConstraint(
            model_name='telegrammessagetemplate',
            constraint=models.UniqueConstraint(fields=('store', 'event_code'), name='unique_store_telegram_template'),
        ),
    ]
