# Generated by Django 5.2.16 on 2026-07-18 14:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0015_finalize_telegram_template_redesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsystemsettings',
            name='immediate_ack_enabled',
            field=models.BooleanField(default=True, verbose_name='немедленное подтверждение'),
        ),
        migrations.AddField(
            model_name='telegramsystemsettings',
            name='immediate_ack_text',
            field=models.CharField(default='Принято', max_length=255, verbose_name='текст подтверждения'),
        ),
        migrations.AddField(
            model_name='telegramsystemsettings',
            name='incoming_mode',
            field=models.CharField(choices=[('webhook', 'Webhook'), ('polling', 'Polling')], default='webhook', max_length=16, verbose_name='режим входящих сообщений'),
        ),
        migrations.AddField(
            model_name='telegramsystemsettings',
            name='webhook_allowed_updates',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='разрешённые типы updates'),
        ),
        migrations.AddField(
            model_name='telegramsystemsettings',
            name='webhook_is_enabled',
            field=models.BooleanField(default=False, verbose_name='webhook зарегистрирован'),
        ),
        migrations.AddField(
            model_name='telegramsystemsettings',
            name='webhook_last_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='webhook проверен'),
        ),
        migrations.AddField(
            model_name='telegramsystemsettings',
            name='webhook_last_error',
            field=models.TextField(blank=True, verbose_name='последняя ошибка webhook'),
        ),
        migrations.AddField(
            model_name='telegramsystemsettings',
            name='webhook_max_connections',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='максимум соединений webhook'),
        ),
        migrations.AddField(
            model_name='telegramsystemsettings',
            name='webhook_registered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='webhook зарегистрирован'),
        ),
        migrations.AddField(
            model_name='telegramsystemsettings',
            name='webhook_secret_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='секрет webhook'),
        ),
        migrations.AddField(
            model_name='telegramsystemsettings',
            name='webhook_url',
            field=models.URLField(blank=True, verbose_name='URL webhook'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('daily_checklist_created', 'Создан ежедневный чек-лист'), ('answer_status_changed', 'Изменён статус ответа'), ('answer_comment_changed', 'Изменён комментарий ответа'), ('daily_checklist_completed', 'Чек-лист завершён'), ('daily_checklist_reopened', 'Чек-лист открыт повторно'), ('checklist_stage_completed', 'Этап чек-листа завершён'), ('telegram_notification_sent', 'Telegram-уведомление отправлено'), ('telegram_notification_failed', 'Ошибка Telegram-уведомления'), ('answer_revised', 'Ответ изменён с указанием причины'), ('template_version_published', 'Версия шаблона опубликована'), ('store_created', 'Магазин создан'), ('store_updated', 'Магазин изменён'), ('store_activated', 'Магазин активирован'), ('store_deactivated', 'Магазин деактивирован'), ('store_deleted', 'Магазин удалён'), ('store_deactivated_with_history', 'Магазин с историей деактивирован'), ('audit_log_cleared', 'Журнал действий очищен'), ('user_created', 'Пользователь создан'), ('user_updated', 'Пользователь изменён'), ('user_activated', 'Пользователь активирован'), ('user_deactivated', 'Пользователь деактивирован'), ('user_role_changed', 'Роль пользователя изменена'), ('user_store_changed', 'Магазин пользователя изменён'), ('user_password_reset', 'Пароль пользователя сброшен'), ('store_employee_created', 'Сотрудник создан'), ('store_employee_updated', 'Сотрудник изменён'), ('store_employee_activated', 'Сотрудник активирован'), ('store_employee_deactivated', 'Сотрудник деактивирован'), ('checklist_question_created', 'Вопрос создан'), ('checklist_question_updated', 'Вопрос изменён'), ('checklist_question_activated', 'Вопрос активирован'), ('checklist_question_deactivated', 'Вопрос деактивирован'), ('checklist_question_deleted', 'Вопрос удалён'), ('checklist_question_removed_from_template', 'Вопрос исключён из новых чек-листов'), ('checklist_questions_reordered', 'Вопросы переупорядочены'), ('store_schedule_updated', 'Расписание магазина изменено'), ('store_notification_settings_updated', 'Настройки уведомлений изменены'), ('telegram_test_message_sent', 'Тест Telegram отправлен'), ('checklist_stage_reopened', 'Этап повторно открыт'), ('shift_assignment_created', 'Назначение на смену создано'), ('shift_assignment_updated', 'Назначение на смену изменено'), ('shift_assignment_deleted', 'Назначение на смену удалено'), ('shift_assignments_bulk_created', 'Назначения на смены созданы массово'), ('telegram_system_settings_updated', 'Системные настройки Telegram изменены'), ('telegram_store_chat_created', 'Telegram-чат создан'), ('telegram_store_chat_updated', 'Telegram-чат изменён'), ('telegram_store_chat_deleted', 'Telegram-чат удалён'), ('telegram_template_updated', 'Шаблон Telegram изменён'), ('telegram_template_created', 'Шаблон Telegram создан'), ('telegram_template_deleted', 'Шаблон Telegram удалён'), ('telegram_template_enabled', 'Шаблон Telegram включён'), ('telegram_template_disabled', 'Шаблон Telegram выключен'), ('telegram_template_reset', 'Шаблон Telegram восстановлен'), ('telegram_template_test_sent', 'Тест шаблона Telegram поставлен в очередь'), ('telegram_binding_approved', 'Привязка Telegram подтверждена'), ('telegram_binding_disabled', 'Привязка Telegram отключена'), ('telegram_task_created', 'Разовая задача создана'), ('telegram_task_completed', 'Разовая задача выполнена'), ('telegram_task_failed', 'Разовая задача не выполнена'), ('telegram_test_sent', 'Тест Telegram поставлен в очередь'), ('telegram_delivery_failed', 'Доставка Telegram завершилась ошибкой'), ('telegram_webhook_registered', 'Webhook Telegram зарегистрирован'), ('telegram_webhook_deleted', 'Webhook Telegram удалён'), ('telegram_webhook_checked', 'Webhook Telegram проверен'), ('telegram_incoming_mode_changed', 'Режим входящих Telegram изменён'), ('telegram_inbound_job_retried', 'Входящая Telegram-команда повторена'), ('store_task_created_by_admin', 'Разовая задача создана через кабинет'), ('store_task_updated', 'Разовая задача изменена'), ('store_task_cancelled', 'Разовая задача отменена')], max_length=50, verbose_name='действие'),
        ),
        migrations.CreateModel(
            name='TelegramInboundJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField(unique=True, verbose_name='Telegram update ID')),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram user ID')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram chat ID')),
                ('update_type', models.CharField(max_length=32, verbose_name='тип update')),
                ('command', models.CharField(blank=True, max_length=64, verbose_name='команда')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=16, verbose_name='статус')),
                ('attempts_count', models.PositiveSmallIntegerField(default=0, verbose_name='попыток')),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='доступно с')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='захвачено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='завершено')),
                ('last_error', models.TextField(blank=True, verbose_name='последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telegram_inbound_jobs', to='checklists.store', verbose_name='магазин')),
                ('update_log', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_job', to='checklists.telegramupdatelog', verbose_name='журнал update')),
            ],
            options={
                'verbose_name': 'входящая Telegram-команда',
                'verbose_name_plural': 'входящие Telegram-команды',
                'ordering': ('available_at', 'id'),
                'indexes': [models.Index(fields=['status', 'available_at'], name='tg_inbound_status_idx'), models.Index(fields=['store', 'status'], name='tg_inbound_store_idx')],
            },
        ),
    ]
