# Generated by Django 5.2 on 2026-07-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0016_telegram_webhook_and_inbound_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsystemsettings',
            name='bot_commands_last_checked_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='команды бота проверены',
            ),
        ),
        migrations.AddField(
            model_name='telegramsystemsettings',
            name='bot_commands_last_error',
            field=models.TextField(
                blank=True,
                verbose_name='последняя ошибка команд бота',
            ),
        ),
        migrations.AddField(
            model_name='telegramsystemsettings',
            name='bot_commands_registered_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='команды бота зарегистрированы',
            ),
        ),
    ]
