# Generated by Django 5.2.16 on 2026-07-18 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0018_telegram_update_response_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeadhoctask',
            old_name='created_by_user',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='stores/logo/', verbose_name='логотип'),
        ),
        migrations.AddField(
            model_name='telegramoutboundmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='удалено в Telegram'),
        ),
        migrations.AddField(
            model_name='telegramoutboundmessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_telegram_messages', to=settings.AUTH_USER_MODEL, verbose_name='удалил'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('daily_checklist_created', 'Создан ежедневный чек-лист'), ('answer_status_changed', 'Изменён статус ответа'), ('answer_comment_changed', 'Изменён комментарий ответа'), ('daily_checklist_completed', 'Чек-лист завершён'), ('daily_checklist_reopened', 'Чек-лист открыт повторно'), ('checklist_stage_completed', 'Этап чек-листа завершён'), ('telegram_notification_sent', 'Telegram-уведомление отправлено'), ('telegram_notification_failed', 'Ошибка Telegram-уведомления'), ('answer_revised', 'Ответ изменён с указанием причины'), ('template_version_published', 'Версия шаблона опубликована'), ('store_created', 'Магазин создан'), ('store_updated', 'Магазин изменён'), ('store_activated', 'Магазин активирован'), ('store_deactivated', 'Магазин деактивирован'), ('store_deleted', 'Магазин удалён'), ('store_deactivated_with_history', 'Магазин с историей деактивирован'), ('audit_log_cleared', 'Журнал действий очищен'), ('user_created', 'Пользователь создан'), ('user_updated', 'Пользователь изменён'), ('user_activated', 'Пользователь активирован'), ('user_deactivated', 'Пользователь деактивирован'), ('user_role_changed', 'Роль пользователя изменена'), ('user_store_changed', 'Магазин пользователя изменён'), ('user_password_reset', 'Пароль пользователя сброшен'), ('user_deleted', 'Пользователь удалён'), ('store_employee_created', 'Сотрудник создан'), ('store_employee_updated', 'Сотрудник изменён'), ('store_employee_activated', 'Сотрудник активирован'), ('store_employee_deactivated', 'Сотрудник деактивирован'), ('checklist_question_created', 'Вопрос создан'), ('checklist_question_updated', 'Вопрос изменён'), ('checklist_question_activated', 'Вопрос активирован'), ('checklist_question_deactivated', 'Вопрос деактивирован'), ('checklist_question_deleted', 'Вопрос удалён'), ('checklist_question_removed_from_template', 'Вопрос исключён из новых чек-листов'), ('checklist_questions_reordered', 'Вопросы переупорядочены'), ('store_schedule_updated', 'Расписание магазина изменено'), ('store_notification_settings_updated', 'Настройки уведомлений изменены'), ('telegram_test_message_sent', 'Тест Telegram отправлен'), ('store_task_deleted', 'Задача магазина удалена'), ('checklist_stage_reopened', 'Этап повторно открыт'), ('shift_assignment_created', 'Назначение на смену создано'), ('shift_assignment_updated', 'Назначение на смену изменено'), ('shift_assignment_deleted', 'Назначение на смену удалено'), ('shift_assignments_bulk_created', 'Назначения на смены созданы массово'), ('telegram_system_settings_updated', 'Системные настройки Telegram изменены'), ('telegram_store_chat_created', 'Telegram-чат создан'), ('telegram_store_chat_updated', 'Telegram-чат изменён'), ('telegram_store_chat_deleted', 'Telegram-чат удалён'), ('telegram_template_updated', 'Шаблон Telegram изменён'), ('telegram_template_created', 'Шаблон Telegram создан'), ('telegram_template_deleted', 'Шаблон Telegram удалён'), ('telegram_template_enabled', 'Шаблон Telegram включён'), ('telegram_template_disabled', 'Шаблон Telegram выключен'), ('telegram_template_reset', 'Шаблон Telegram восстановлен'), ('telegram_template_test_sent', 'Тест шаблона Telegram поставлен в очередь'), ('telegram_binding_approved', 'Привязка Telegram подтверждена'), ('telegram_binding_disabled', 'Привязка Telegram отключена'), ('telegram_task_created', 'Разовая задача создана'), ('telegram_task_completed', 'Разовая задача выполнена'), ('telegram_task_failed', 'Разовая задача не выполнена'), ('telegram_test_sent', 'Тест Telegram поставлен в очередь'), ('telegram_delivery_failed', 'Доставка Telegram завершилась ошибкой'), ('telegram_webhook_registered', 'Webhook Telegram зарегистрирован'), ('telegram_webhook_deleted', 'Webhook Telegram удалён'), ('telegram_webhook_checked', 'Webhook Telegram проверен'), ('telegram_incoming_mode_changed', 'Режим входящих Telegram изменён'), ('telegram_inbound_job_retried', 'Входящая Telegram-команда повторена'), ('store_task_created_by_admin', 'Разовая задача создана через кабинет'), ('store_task_updated', 'Разовая задача изменена'), ('store_task_cancelled', 'Разовая задача отменена')], max_length=50, verbose_name='действие'),
        ),
        migrations.AlterField(
            model_name='telegramoutboundmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('deleted', 'Удалено в Telegram')], default='pending', max_length=16, verbose_name='статус'),
        ),
        migrations.CreateModel(
            name='TelegramUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(unique=True, verbose_name='Telegram user ID')),
                ('telegram_chat_id', models.BigIntegerField(verbose_name='Telegram chat ID')),
                ('telegram_username', models.CharField(blank=True, max_length=64, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=128, verbose_name='фамилия')),
                ('is_verified', models.BooleanField(default=False, verbose_name='подтверждён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Telegram-профиль пользователя',
                'verbose_name_plural': 'Telegram-профили пользователей',
                'ordering': ('user__username',),
            },
        ),
    ]
