# Generated by Django 5.2.16 on 2026-07-18 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_existing_user_store_links(apps, schema_editor):
    EmployeeProfile = apps.get_model('checklists', 'EmployeeProfile')
    TelegramStoreBinding = apps.get_model('checklists', 'TelegramStoreBinding')
    TelegramUserProfile = apps.get_model('checklists', 'TelegramUserProfile')
    UserStoreMembership = apps.get_model('checklists', 'UserStoreMembership')
    database = schema_editor.connection.alias

    profile_roles = {
        'store_director': 'director',
        'store_account': 'employee',
    }
    profile_by_user = {}
    for profile in EmployeeProfile.objects.using(database).exclude(
        store_id=None
    ).iterator():
        profile_by_user[profile.user_id] = profile
        role = profile_roles.get(profile.role, 'employee')
        UserStoreMembership.objects.using(database).update_or_create(
            user_id=profile.user_id,
            store_id=profile.store_id,
            defaults={
                'role_in_store': role,
                'is_active': profile.is_active,
            },
        )

    for binding in TelegramStoreBinding.objects.using(database).exclude(
        user_id=None
    ).iterator():
        profile = profile_by_user.get(binding.user_id)
        role = (
            profile_roles.get(profile.role)
            if profile and profile.store_id == binding.store_id
            else 'employee'
        )
        UserStoreMembership.objects.using(database).update_or_create(
            user_id=binding.user_id,
            store_id=binding.store_id,
            defaults={
                'role_in_store': role or 'employee',
                'is_active': binding.is_active,
            },
        )
        telegram_conflict = TelegramUserProfile.objects.using(database).filter(
            telegram_user_id=binding.telegram_user_id
        ).exclude(user_id=binding.user_id).exists()
        if telegram_conflict:
            continue
        TelegramUserProfile.objects.using(database).update_or_create(
            user_id=binding.user_id,
            defaults={
                'telegram_user_id': binding.telegram_user_id,
                'telegram_chat_id': binding.telegram_chat_id,
                'telegram_username': binding.username,
                'first_name': binding.first_name,
                'last_name': binding.last_name,
                'is_verified': binding.is_active,
            },
        )


def keep_memberships_on_reverse(apps, schema_editor):
    # Reversing the schema removes the through table. Legacy EmployeeProfile
    # and TelegramStoreBinding rows remain untouched.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0019_rename_created_by_user_storeadhoctask_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('daily_checklist_created', 'Создан ежедневный чек-лист'), ('answer_status_changed', 'Изменён статус ответа'), ('answer_comment_changed', 'Изменён комментарий ответа'), ('daily_checklist_completed', 'Чек-лист завершён'), ('daily_checklist_reopened', 'Чек-лист открыт повторно'), ('checklist_stage_completed', 'Этап чек-листа завершён'), ('telegram_notification_sent', 'Telegram-уведомление отправлено'), ('telegram_notification_failed', 'Ошибка Telegram-уведомления'), ('answer_revised', 'Ответ изменён с указанием причины'), ('template_version_published', 'Версия шаблона опубликована'), ('store_created', 'Магазин создан'), ('store_updated', 'Магазин изменён'), ('store_activated', 'Магазин активирован'), ('store_deactivated', 'Магазин деактивирован'), ('store_deleted', 'Магазин удалён'), ('store_deactivated_with_history', 'Магазин с историей деактивирован'), ('audit_log_cleared', 'Журнал действий очищен'), ('user_created', 'Пользователь создан'), ('user_updated', 'Пользователь изменён'), ('user_activated', 'Пользователь активирован'), ('user_deactivated', 'Пользователь деактивирован'), ('user_role_changed', 'Роль пользователя изменена'), ('user_store_changed', 'Магазин пользователя изменён'), ('user_password_reset', 'Пароль пользователя сброшен'), ('user_deleted', 'Пользователь удалён'), ('user_store_membership_created', 'Пользователь добавлен в магазин'), ('user_store_membership_updated', 'Роль пользователя в магазине изменена'), ('user_store_membership_deleted', 'Пользователь удалён из магазина'), ('store_employee_created', 'Сотрудник создан'), ('store_employee_updated', 'Сотрудник изменён'), ('store_employee_activated', 'Сотрудник активирован'), ('store_employee_deactivated', 'Сотрудник деактивирован'), ('checklist_question_created', 'Вопрос создан'), ('checklist_question_updated', 'Вопрос изменён'), ('checklist_question_activated', 'Вопрос активирован'), ('checklist_question_deactivated', 'Вопрос деактивирован'), ('checklist_question_deleted', 'Вопрос удалён'), ('checklist_question_removed_from_template', 'Вопрос исключён из новых чек-листов'), ('checklist_questions_reordered', 'Вопросы переупорядочены'), ('store_schedule_updated', 'Расписание магазина изменено'), ('store_notification_settings_updated', 'Настройки уведомлений изменены'), ('telegram_test_message_sent', 'Тест Telegram отправлен'), ('store_task_deleted', 'Задача магазина удалена'), ('checklist_stage_reopened', 'Этап повторно открыт'), ('shift_assignment_created', 'Назначение на смену создано'), ('shift_assignment_updated', 'Назначение на смену изменено'), ('shift_assignment_deleted', 'Назначение на смену удалено'), ('shift_assignments_bulk_created', 'Назначения на смены созданы массово'), ('telegram_system_settings_updated', 'Системные настройки Telegram изменены'), ('telegram_store_chat_created', 'Telegram-чат создан'), ('telegram_store_chat_updated', 'Telegram-чат изменён'), ('telegram_store_chat_deleted', 'Telegram-чат удалён'), ('telegram_template_updated', 'Шаблон Telegram изменён'), ('telegram_template_created', 'Шаблон Telegram создан'), ('telegram_template_deleted', 'Шаблон Telegram удалён'), ('telegram_template_enabled', 'Шаблон Telegram включён'), ('telegram_template_disabled', 'Шаблон Telegram выключен'), ('telegram_template_reset', 'Шаблон Telegram восстановлен'), ('telegram_template_test_sent', 'Тест шаблона Telegram поставлен в очередь'), ('telegram_binding_approved', 'Привязка Telegram подтверждена'), ('telegram_binding_disabled', 'Привязка Telegram отключена'), ('telegram_profile_reassigned', 'Пользователь Telegram-привязки изменён'), ('telegram_profile_disconnected', 'Telegram отвязан от пользователя'), ('telegram_task_created', 'Разовая задача создана'), ('telegram_task_completed', 'Разовая задача выполнена'), ('telegram_task_failed', 'Разовая задача не выполнена'), ('telegram_test_sent', 'Тест Telegram поставлен в очередь'), ('telegram_delivery_failed', 'Доставка Telegram завершилась ошибкой'), ('telegram_webhook_registered', 'Webhook Telegram зарегистрирован'), ('telegram_webhook_deleted', 'Webhook Telegram удалён'), ('telegram_webhook_checked', 'Webhook Telegram проверен'), ('telegram_incoming_mode_changed', 'Режим входящих Telegram изменён'), ('telegram_inbound_job_retried', 'Входящая Telegram-команда повторена'), ('store_task_created_by_admin', 'Разовая задача создана через кабинет'), ('store_task_updated', 'Разовая задача изменена'), ('store_task_cancelled', 'Разовая задача отменена')], max_length=50, verbose_name='действие'),
        ),
        migrations.CreateModel(
            name='UserStoreMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_store', models.CharField(choices=[('director', 'Директор'), ('employee', 'Сотрудник'), ('administrator', 'Администратор')], max_length=20, verbose_name='роль в магазине')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='checklists.store', verbose_name='магазин')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_memberships', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'связь пользователя с магазином',
                'verbose_name_plural': 'связи пользователей с магазинами',
                'ordering': ('store__name', 'user__username'),
            },
        ),
        migrations.AddField(
            model_name='store',
            name='users',
            field=models.ManyToManyField(related_name='stores', through='checklists.UserStoreMembership', to=settings.AUTH_USER_MODEL, verbose_name='пользователи'),
        ),
        migrations.AddIndex(
            model_name='userstoremembership',
            index=models.Index(fields=['user', 'is_active'], name='membership_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='userstoremembership',
            index=models.Index(fields=['store', 'role_in_store', 'is_active'], name='membership_store_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='userstoremembership',
            constraint=models.UniqueConstraint(fields=('user', 'store'), name='unique_user_store_membership'),
        ),
        migrations.RunPython(
            preserve_existing_user_store_links,
            keep_memberships_on_reverse,
        ),
    ]
