# Generated by Django 5.2.16 on 2026-07-18 19:31

import checklists.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_existing_store_availability(apps, schema_editor):
    StoreChecklistSchedule = apps.get_model(
        'checklists',
        'StoreChecklistSchedule',
    )
    StoreChecklistSchedule.objects.using(
        schema_editor.connection.alias
    ).all().update(working_weekdays=[0, 1, 2, 3, 4, 5, 6])


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0020_alter_auditlog_action_userstoremembership_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDayStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('status', models.CharField(choices=[('normal', 'Обычный день'), ('testing', 'Тестирование'), ('day_off', 'Выходной'), ('emergency', 'Чрезвычайная ситуация')], default='normal', max_length=16, verbose_name='статус дня')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
            ],
            options={
                'verbose_name': 'статус дня магазина',
                'verbose_name_plural': 'статусы дней магазинов',
                'ordering': ('-date', 'store__name'),
            },
        ),
        migrations.AddField(
            model_name='dailychecklist',
            name='day_status',
            field=models.CharField(choices=[('normal', 'Обычный день'), ('testing', 'Тестирование'), ('day_off', 'Выходной'), ('emergency', 'Чрезвычайная ситуация')], default='normal', max_length=16, verbose_name='статус дня'),
        ),
        migrations.AddField(
            model_name='storechecklistschedule',
            name='working_weekdays',
            field=models.JSONField(default=checklists.models.default_working_weekdays, help_text='Номера дней: понедельник — 0, воскресенье — 6.', verbose_name='рабочие дни недели'),
        ),
        migrations.RunPython(
            preserve_existing_store_availability,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='storeemployee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_employee_records', to=settings.AUTH_USER_MODEL, verbose_name='учётная запись'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('daily_checklist_created', 'Создан ежедневный чек-лист'), ('answer_status_changed', 'Изменён статус ответа'), ('answer_comment_changed', 'Изменён комментарий ответа'), ('daily_checklist_completed', 'Чек-лист завершён'), ('daily_checklist_reopened', 'Чек-лист открыт повторно'), ('checklist_stage_completed', 'Этап чек-листа завершён'), ('telegram_notification_sent', 'Telegram-уведомление отправлено'), ('telegram_notification_failed', 'Ошибка Telegram-уведомления'), ('answer_revised', 'Ответ изменён с указанием причины'), ('template_version_published', 'Версия шаблона опубликована'), ('store_created', 'Магазин создан'), ('store_updated', 'Магазин изменён'), ('store_activated', 'Магазин активирован'), ('store_deactivated', 'Магазин деактивирован'), ('store_deleted', 'Магазин удалён'), ('store_deactivated_with_history', 'Магазин с историей деактивирован'), ('audit_log_cleared', 'Журнал действий очищен'), ('user_created', 'Пользователь создан'), ('user_updated', 'Пользователь изменён'), ('user_activated', 'Пользователь активирован'), ('user_deactivated', 'Пользователь деактивирован'), ('user_role_changed', 'Роль пользователя изменена'), ('user_store_changed', 'Магазин пользователя изменён'), ('user_password_reset', 'Пароль пользователя сброшен'), ('user_deleted', 'Пользователь удалён'), ('user_store_membership_created', 'Пользователь добавлен в магазин'), ('user_store_membership_updated', 'Роль пользователя в магазине изменена'), ('user_store_membership_deleted', 'Пользователь удалён из магазина'), ('store_employee_created', 'Сотрудник создан'), ('store_employee_updated', 'Сотрудник изменён'), ('store_employee_activated', 'Сотрудник активирован'), ('store_employee_deactivated', 'Сотрудник деактивирован'), ('checklist_question_created', 'Вопрос создан'), ('checklist_question_updated', 'Вопрос изменён'), ('checklist_question_activated', 'Вопрос активирован'), ('checklist_question_deactivated', 'Вопрос деактивирован'), ('checklist_question_deleted', 'Вопрос удалён'), ('checklist_question_removed_from_template', 'Вопрос исключён из новых чек-листов'), ('checklist_questions_reordered', 'Вопросы переупорядочены'), ('store_schedule_updated', 'Расписание магазина изменено'), ('store_day_status_updated', 'Статус дня магазина изменён'), ('store_notification_settings_updated', 'Настройки уведомлений изменены'), ('telegram_test_message_sent', 'Тест Telegram отправлен'), ('store_task_deleted', 'Задача магазина удалена'), ('checklist_stage_reopened', 'Этап повторно открыт'), ('shift_assignment_created', 'Назначение на смену создано'), ('shift_assignment_updated', 'Назначение на смену изменено'), ('shift_assignment_deleted', 'Назначение на смену удалено'), ('shift_assignments_bulk_created', 'Назначения на смены созданы массово'), ('employee_schedule_reminder_queued', 'Напоминание о графике поставлено в очередь'), ('telegram_system_settings_updated', 'Системные настройки Telegram изменены'), ('telegram_store_chat_created', 'Telegram-чат создан'), ('telegram_store_chat_updated', 'Telegram-чат изменён'), ('telegram_store_chat_deleted', 'Telegram-чат удалён'), ('telegram_template_updated', 'Шаблон Telegram изменён'), ('telegram_template_created', 'Шаблон Telegram создан'), ('telegram_template_deleted', 'Шаблон Telegram удалён'), ('telegram_template_enabled', 'Шаблон Telegram включён'), ('telegram_template_disabled', 'Шаблон Telegram выключен'), ('telegram_template_reset', 'Шаблон Telegram восстановлен'), ('telegram_template_test_sent', 'Тест шаблона Telegram поставлен в очередь'), ('telegram_binding_approved', 'Привязка Telegram подтверждена'), ('telegram_binding_disabled', 'Привязка Telegram отключена'), ('telegram_profile_reassigned', 'Пользователь Telegram-привязки изменён'), ('telegram_profile_disconnected', 'Telegram отвязан от пользователя'), ('telegram_task_created', 'Разовая задача создана'), ('telegram_task_completed', 'Разовая задача выполнена'), ('telegram_task_failed', 'Разовая задача не выполнена'), ('telegram_test_sent', 'Тест Telegram поставлен в очередь'), ('telegram_delivery_failed', 'Доставка Telegram завершилась ошибкой'), ('telegram_webhook_registered', 'Webhook Telegram зарегистрирован'), ('telegram_webhook_deleted', 'Webhook Telegram удалён'), ('telegram_webhook_checked', 'Webhook Telegram проверен'), ('telegram_incoming_mode_changed', 'Режим входящих Telegram изменён'), ('telegram_inbound_job_retried', 'Входящая Telegram-команда повторена'), ('store_task_created_by_admin', 'Разовая задача создана через кабинет'), ('store_task_updated', 'Разовая задача изменена'), ('store_task_cancelled', 'Разовая задача отменена')], max_length=50, verbose_name='действие'),
        ),
        migrations.AddConstraint(
            model_name='storeemployee',
            constraint=models.UniqueConstraint(fields=('store', 'user'), name='unique_store_employee_user'),
        ),
        migrations.AddField(
            model_name='storedaystatus',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_store_day_statuses', to=settings.AUTH_USER_MODEL, verbose_name='изменил'),
        ),
        migrations.AddField(
            model_name='storedaystatus',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_statuses', to='checklists.store', verbose_name='магазин'),
        ),
        migrations.AddIndex(
            model_name='storedaystatus',
            index=models.Index(fields=['store', 'date', 'status'], name='store_day_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='storedaystatus',
            constraint=models.UniqueConstraint(fields=('store', 'date'), name='unique_store_day_status'),
        ),
    ]
