# Generated by Django 5.2.16 on 2026-07-18 20:23

from datetime import time

import django.db.models.deletion
from django.db import migrations, models


def create_default_shift_templates(apps, schema_editor):
    Store = apps.get_model('checklists', 'Store')
    ShiftTemplate = apps.get_model('checklists', 'ShiftTemplate')
    database = schema_editor.connection.alias
    defaults = (
        ('День', 'work', time(10), time(22), 10),
        ('Сервис', 'service', time(9), time(18), 20),
        ('КЦ', 'work', time(9), time(21), 30),
    )
    templates = []
    for store_id in Store.objects.using(database).values_list('pk', flat=True):
        for name, shift_type, shift_start, shift_end, sort_order in defaults:
            templates.append(
                ShiftTemplate(
                    store_id=store_id,
                    name=name,
                    shift_type=shift_type,
                    shift_start=shift_start,
                    shift_end=shift_end,
                    sort_order=sort_order,
                )
            )
    ShiftTemplate.objects.using(database).bulk_create(templates)


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0021_storedaystatus_dailychecklist_day_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyshiftassignment',
            name='shift_type',
            field=models.CharField(choices=[('work', 'Работа'), ('day_off', 'Выходной'), ('vacation', 'Отпуск'), ('sick_leave', 'Больничный'), ('service', 'Смена сервис'), ('personal', 'Личное отсутствие')], default='work', max_length=20, verbose_name='тип смены'),
        ),
        migrations.AddField(
            model_name='storeemployee',
            name='department',
            field=models.CharField(choices=[('service', 'Сервис'), ('call_center', 'КЦ'), ('store', 'Магазин')], default='store', max_length=20, verbose_name='подразделение'),
        ),
        migrations.AddField(
            model_name='storeemployee',
            name='position',
            field=models.CharField(blank=True, max_length=150, verbose_name='должность'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('daily_checklist_created', 'Создан ежедневный чек-лист'), ('answer_status_changed', 'Изменён статус ответа'), ('answer_comment_changed', 'Изменён комментарий ответа'), ('daily_checklist_completed', 'Чек-лист завершён'), ('daily_checklist_reopened', 'Чек-лист открыт повторно'), ('checklist_stage_completed', 'Этап чек-листа завершён'), ('telegram_notification_sent', 'Telegram-уведомление отправлено'), ('telegram_notification_failed', 'Ошибка Telegram-уведомления'), ('answer_revised', 'Ответ изменён с указанием причины'), ('template_version_published', 'Версия шаблона опубликована'), ('store_created', 'Магазин создан'), ('store_updated', 'Магазин изменён'), ('store_activated', 'Магазин активирован'), ('store_deactivated', 'Магазин деактивирован'), ('store_deleted', 'Магазин удалён'), ('store_deactivated_with_history', 'Магазин с историей деактивирован'), ('audit_log_cleared', 'Журнал действий очищен'), ('user_created', 'Пользователь создан'), ('user_updated', 'Пользователь изменён'), ('user_activated', 'Пользователь активирован'), ('user_deactivated', 'Пользователь деактивирован'), ('user_role_changed', 'Роль пользователя изменена'), ('user_store_changed', 'Магазин пользователя изменён'), ('user_password_reset', 'Пароль пользователя сброшен'), ('user_deleted', 'Пользователь удалён'), ('user_store_membership_created', 'Пользователь добавлен в магазин'), ('user_store_membership_updated', 'Роль пользователя в магазине изменена'), ('user_store_membership_deleted', 'Пользователь удалён из магазина'), ('store_employee_created', 'Сотрудник создан'), ('store_employee_updated', 'Сотрудник изменён'), ('store_employee_activated', 'Сотрудник активирован'), ('store_employee_deactivated', 'Сотрудник деактивирован'), ('checklist_question_created', 'Вопрос создан'), ('checklist_question_updated', 'Вопрос изменён'), ('checklist_question_activated', 'Вопрос активирован'), ('checklist_question_deactivated', 'Вопрос деактивирован'), ('checklist_question_deleted', 'Вопрос удалён'), ('checklist_question_removed_from_template', 'Вопрос исключён из новых чек-листов'), ('checklist_questions_reordered', 'Вопросы переупорядочены'), ('store_schedule_updated', 'Расписание магазина изменено'), ('store_day_status_updated', 'Статус дня магазина изменён'), ('store_notification_settings_updated', 'Настройки уведомлений изменены'), ('telegram_test_message_sent', 'Тест Telegram отправлен'), ('store_task_deleted', 'Задача магазина удалена'), ('checklist_stage_reopened', 'Этап повторно открыт'), ('shift_assignment_created', 'Назначение на смену создано'), ('shift_assignment_updated', 'Назначение на смену изменено'), ('shift_assignment_deleted', 'Назначение на смену удалено'), ('shift_assignments_bulk_created', 'Назначения на смены созданы массово'), ('shift_template_created', 'Шаблон смены создан'), ('shift_template_updated', 'Шаблон смены изменён'), ('shift_template_deleted', 'Шаблон смены удалён'), ('employee_schedule_reminder_queued', 'Напоминание о графике поставлено в очередь'), ('telegram_system_settings_updated', 'Системные настройки Telegram изменены'), ('telegram_store_chat_created', 'Telegram-чат создан'), ('telegram_store_chat_updated', 'Telegram-чат изменён'), ('telegram_store_chat_deleted', 'Telegram-чат удалён'), ('telegram_template_updated', 'Шаблон Telegram изменён'), ('telegram_template_created', 'Шаблон Telegram создан'), ('telegram_template_deleted', 'Шаблон Telegram удалён'), ('telegram_template_enabled', 'Шаблон Telegram включён'), ('telegram_template_disabled', 'Шаблон Telegram выключен'), ('telegram_template_reset', 'Шаблон Telegram восстановлен'), ('telegram_template_test_sent', 'Тест шаблона Telegram поставлен в очередь'), ('telegram_binding_approved', 'Привязка Telegram подтверждена'), ('telegram_binding_disabled', 'Привязка Telegram отключена'), ('telegram_profile_reassigned', 'Пользователь Telegram-привязки изменён'), ('telegram_profile_disconnected', 'Telegram отвязан от пользователя'), ('telegram_task_created', 'Разовая задача создана'), ('telegram_task_completed', 'Разовая задача выполнена'), ('telegram_task_failed', 'Разовая задача не выполнена'), ('telegram_test_sent', 'Тест Telegram поставлен в очередь'), ('telegram_delivery_failed', 'Доставка Telegram завершилась ошибкой'), ('telegram_webhook_registered', 'Webhook Telegram зарегистрирован'), ('telegram_webhook_deleted', 'Webhook Telegram удалён'), ('telegram_webhook_checked', 'Webhook Telegram проверен'), ('telegram_incoming_mode_changed', 'Режим входящих Telegram изменён'), ('telegram_inbound_job_retried', 'Входящая Telegram-команда повторена'), ('store_task_created_by_admin', 'Разовая задача создана через кабинет'), ('store_task_updated', 'Разовая задача изменена'), ('store_task_cancelled', 'Разовая задача отменена')], max_length=50, verbose_name='действие'),
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('shift_type', models.CharField(choices=[('work', 'Работа'), ('day_off', 'Выходной'), ('vacation', 'Отпуск'), ('sick_leave', 'Больничный'), ('service', 'Смена сервис'), ('personal', 'Личное отсутствие')], default='work', max_length=20, verbose_name='тип смены')),
                ('shift_start', models.TimeField(blank=True, null=True, verbose_name='начало смены')),
                ('shift_end', models.TimeField(blank=True, null=True, verbose_name='окончание смены')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='checklists.store', verbose_name='магазин')),
            ],
            options={
                'verbose_name': 'шаблон смены',
                'verbose_name_plural': 'шаблоны смен',
                'ordering': ('sort_order', 'name', 'id'),
                'constraints': [models.UniqueConstraint(fields=('store', 'name'), name='unique_store_shift_template_name')],
            },
        ),
        migrations.RunPython(
            create_default_shift_templates,
            migrations.RunPython.noop,
        ),
    ]
