# Generated by Django 5.2.16 on 2026-07-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0022_dailyshiftassignment_shift_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyshiftassignment',
            name='shift_type',
            field=models.CharField(choices=[('work', 'Работа'), ('night', 'Ночная смена'), ('day_off', 'Выходной'), ('vacation', 'Отпуск'), ('sick_leave', 'Больничный'), ('service', 'Смена сервис'), ('personal', 'Личное отсутствие')], default='work', max_length=20, verbose_name='тип смены'),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='shift_type',
            field=models.CharField(choices=[('work', 'Работа'), ('night', 'Ночная смена'), ('day_off', 'Выходной'), ('vacation', 'Отпуск'), ('sick_leave', 'Больничный'), ('service', 'Смена сервис'), ('personal', 'Личное отсутствие')], default='work', max_length=20, verbose_name='тип смены'),
        ),
    ]
