# Generated by Django 5.2.16 on 2026-07-20 10:31

import django.core.validators
from datetime import timedelta

from django.db import migrations, models


def populate_completion_available_at(apps, schema_editor):
    DailyChecklistStage = apps.get_model(
        'checklists',
        'DailyChecklistStage',
    )
    StoreChecklistSchedule = apps.get_model(
        'checklists',
        'StoreChecklistSchedule',
    )
    schedules = {
        schedule.store_id: schedule
        for schedule in StoreChecklistSchedule.objects.all().iterator()
    }
    field_by_section = {
        'opening': 'morning_completion_window_hours',
        'during_day': 'day_completion_window_hours',
        'closing': 'evening_completion_window_hours',
    }
    for stage in DailyChecklistStage.objects.select_related(
        'daily_checklist'
    ).iterator():
        schedule = schedules.get(stage.daily_checklist.store_id)
        window_hours = (
            getattr(schedule, field_by_section[stage.section_code])
            if schedule is not None
            else 2
        )
        stage.completion_available_at = max(
            stage.opens_at,
            stage.deadline_at - timedelta(hours=window_hours),
        )
        stage.save(update_fields=('completion_available_at',))


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0023_alter_dailyshiftassignment_shift_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckliststage',
            name='completion_available_at',
            field=models.DateTimeField(null=True, verbose_name='завершение доступно с'),
        ),
        migrations.AddField(
            model_name='storechecklistschedule',
            name='day_completion_window_hours',
            field=models.PositiveSmallIntegerField(default=2, help_text='Изменение применяется только к новым ежедневным чек-листам', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='окно завершения дневного этапа, часов'),
        ),
        migrations.AddField(
            model_name='storechecklistschedule',
            name='evening_completion_window_hours',
            field=models.PositiveSmallIntegerField(default=2, help_text='Изменение применяется только к новым ежедневным чек-листам', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='окно завершения вечернего этапа, часов'),
        ),
        migrations.AddField(
            model_name='storechecklistschedule',
            name='morning_completion_window_hours',
            field=models.PositiveSmallIntegerField(default=2, help_text='Изменение применяется только к новым ежедневным чек-листам', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='окно завершения утреннего этапа, часов'),
        ),
        migrations.RunPython(
            populate_completion_available_at,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='dailycheckliststage',
            name='completion_available_at',
            field=models.DateTimeField(verbose_name='завершение доступно с'),
        ),
        migrations.AddConstraint(
            model_name='storechecklistschedule',
            constraint=models.CheckConstraint(condition=models.Q(('morning_completion_window_hours__gte', 0), ('morning_completion_window_hours__lte', 12)), name='schedule_morning_completion_window_0_12'),
        ),
        migrations.AddConstraint(
            model_name='storechecklistschedule',
            constraint=models.CheckConstraint(condition=models.Q(('day_completion_window_hours__gte', 0), ('day_completion_window_hours__lte', 12)), name='schedule_day_completion_window_0_12'),
        ),
        migrations.AddConstraint(
            model_name='storechecklistschedule',
            constraint=models.CheckConstraint(condition=models.Q(('evening_completion_window_hours__gte', 0), ('evening_completion_window_hours__lte', 12)), name='schedule_evening_completion_window_0_12'),
        ),
    ]
