# Generated by Django 5.2.16 on 2026-08-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0029_price_tag_available_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepricetagtemplate',
            name='print_mode',
            field=models.CharField(choices=[('color', 'Цветной принтер'), ('monochrome', 'Чёрно-белый принтер')], default='color', max_length=20, verbose_name='режим печати'),
        ),
        migrations.AddField(
            model_name='storepricetagtemplate',
            name='qr_utm_parameters',
            field=models.CharField(blank=True, default='', help_text='Например: utm_source=price_tag&utm_medium=offline. Параметры добавятся к ссылке товара в QR-коде.', max_length=500, verbose_name='UTM-параметры для QR-кода'),
        ),
    ]
