# Generated by Django 5.2.16 on 2026-08-01 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0033_limit_price_tag_properties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storepricetagcategory',
            name='available_property_names',
            field=models.JSONField(blank=True, default=list, verbose_name='найденные свойства категории'),
        ),
        migrations.CreateModel(
            name='PriceTagGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.PositiveSmallIntegerField(default=0, verbose_name='ценников')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_tag_generations', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tag_generations', to='checklists.store', verbose_name='магазин')),
            ],
            options={
                'verbose_name': 'генерация ценников',
                'verbose_name_plural': 'генерации ценников',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PriceTagGenerationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=2000, verbose_name='ссылка товара')),
                ('product_name', models.CharField(max_length=500, verbose_name='название из h1')),
                ('profile_name', models.CharField(max_length=120, verbose_name='интернет-магазин')),
                ('category_name', models.CharField(blank=True, max_length=120, verbose_name='категория')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.pricetaggeneration', verbose_name='генерация')),
            ],
            options={
                'verbose_name': 'товар в генерации ценников',
                'verbose_name_plural': 'товары в генерации ценников',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PriceTagNameCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=500, verbose_name='ссылка товара')),
                ('original_name', models.CharField(max_length=500, verbose_name='исходное название')),
                ('corrected_name', models.CharField(max_length=500, verbose_name='исправленное название')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='использований')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_corrections', to='checklists.storepricetagcategory', verbose_name='категория')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_tag_name_corrections', to=settings.AUTH_USER_MODEL, verbose_name='исправил')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_corrections', to='checklists.storepricetagtemplate', verbose_name='профиль сайта')),
            ],
            options={
                'verbose_name': 'правка названия ценника',
                'verbose_name_plural': 'правки названий ценников',
                'ordering': ('-updated_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('profile', 'source_url'), name='unique_price_tag_name_correction_url')],
            },
        ),
    ]
