# Generated by Django 5.2.16 on 2026-08-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0034_storepricetagcategory_available_property_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storepricetagtemplate',
            name='heading',
        ),
        migrations.AddField(
            model_name='storepricetagcategory',
            name='promotion_details',
            field=models.CharField(blank=True, default='', help_text='Например: условия акции уточняйте у менеджера.', max_length=200, verbose_name='условия акции'),
        ),
        migrations.AddField(
            model_name='storepricetagcategory',
            name='promotion_title',
            field=models.CharField(blank=True, default='', help_text='Например: БЕСПЛАТНАЯ УСТАНОВКА.', max_length=100, verbose_name='заголовок акции'),
        ),
    ]
